# 15 — PCA por dimensión

Objetivo general del cuaderno:
Vamos a resolver qué hacer con los casos de baja cobertura y valores extremos. Vamos a resolver la estrategia de imputación sobre el resto, estandarizar por dimensión y correr PCA por dimensión con sus diagnósticos correspondientes.

## 1.  importacion de librerias y carga de datos

In [5]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from pathlib import Path

pd.set_option("display.max_columns", None)

In [6]:
IN_PATH = Path("data/processed/14_pais_features.xlsx")  # ajustá la ruta si tu archivo está en otro lugar
df_pais_features = pd.read_excel(IN_PATH, sheet_name="pais_features", index_col=0)

print(f"Shape df_pais_features: {df_pais_features.shape}")
df_pais_features.head()

Shape df_pais_features: (193, 2058)

,AG.LND.TOTL.K2_media,BG.GSR.NFSV.GD.ZS_media,BM.GSR.CMCP.ZS_media,BM.GSR.FCTY.CD_media,BM.GSR.GNFS.CD_media,BM.GSR.INSF.ZS_media,BM.GSR.MRCH.CD_media,BM.GSR.NFSV.CD_media,BM.GSR.ROYL.CD_media,BM.GSR.TOTL.CD_media,BM.GSR.TRAN.ZS_media,BM.GSR.TRVL.ZS_media,BM.KLT.DINV.CD.WD_media,BM.KLT.DINV.WD.GD.ZS_media,BM.TRF.PRVT.CD_media,BM.TRF.PWKR.CD.DT_media,BN.CAB.XOKA.CD_media,BN.CAB.XOKA.GD.ZS_media,BN.FIN.TOTL.CD_media,BN.GSR.FCTY.CD_media,BN.GSR.GNFS.CD_media,BN.GSR.MRCH.CD_media,BN.KAC.EOMS.CD_media,BN.KLT.DINV.CD_media,BN.KLT.PTXL.CD_media,BN.RES.INCL.CD_media,BN.TRF.CURR.CD_media,BN.TRF.KOGT.CD_media,BX.GRT.EXTA.CD.WD_media,BX.GRT.TECH.CD.WD_media,BX.GSR.CCIS.CD_media,BX.GSR.CCIS.ZS_media,BX.GSR.CMCP.ZS_media,BX.GSR.FCTY.CD_media,BX.GSR.GNFS.CD_media,BX.GSR.INSF.ZS_media,BX.GSR.MRCH.CD_media,BX.GSR.NFSV.CD_media,BX.GSR.ROYL.CD_media,BX.GSR.TOTL.CD_media,BX.GSR.TRAN.ZS_media,BX.GSR.TRVL.ZS_media,BX.KLT.DINV.CD.WD_media,BX.KLT.DINV.WD.GD.ZS_media,BX.PEF.TOTL.CD.WD_media,BX.TRF.CURR.CD_media,BX.TRF.PWKR.CD_media,BX.TRF.PWKR.CD.DT_media,BX.TRF.PWKR.DT.GD.ZS_media,DC.DAC.TOTL.CD_media,DT.ODA.ODAT.CD_media,DT.ODA.ODAT.GN.ZS_media,DT.ODA.ODAT.PC.ZS_media,EG.ELC.ACCS.RU.ZS_media,EG.ELC.ACCS.UR.ZS_media,EG.ELC.ACCS.ZS_media,EG.IMP.CONS.ZS_media,EG.USE.ELEC.KH.PC_media,EG.USE.PCAP.KG.OE_media,EN.POP.DNST_media,FB.ATM.TOTL.P5_media,FB.CBK.BRCH.P5_media,FD.AST.PRVT.GD.ZS_media,FD.RES.LIQU.AS.ZS_media,FI.RES.TOTL.CD_media,FI.RES.TOTL.MO_media,FI.RES.XGLD.CD_media,FM.AST.CGOV.ZG.M3_media,FM.AST.DOMO.ZG.M3_media,FM.AST.DOMS.CN_media,FM.AST.NFRG.CN_media,FM.AST.PRVT.GD.ZS_media,FM.AST.PRVT.ZG.M3_media,FM.LBL.BMNY.CN_media,FM.LBL.BMNY.GD.ZS_media,FM.LBL.BMNY.IR.ZS_media,FM.LBL.BMNY.ZG_media,FR.INR.DPST_media,FR.INR.LEND_media,FR.INR.RINR_media,FS.AST.CGOV.GD.ZS_media,FS.AST.PRVT.GD.ZS_media,GB.XPD.RSDV.GD.ZS_media,GC.NFN.TOTL.GD.ZS_media,GC.NLD.TOTL.GD.ZS_media,GC.REV.GOTR.CN_media,GC.REV.GOTR.ZS_media,GC.REV.XGRT.CN_media,GC.REV.XGRT.GD.ZS_media,GC.TAX.GSRV.CN_media,GC.TAX.GSRV.RV.ZS_media,GC.TAX.GSRV.VA.ZS_media,GC.TAX.IMPT.CN_media,GC.TAX.IMPT.ZS_media,GC.TAX.INTT.CN_media,GC.TAX.INTT.RV.ZS_media,GC.TAX.OTHR.CN_media,GC.TAX.OTHR.RV.ZS_media,GC.TAX.TOTL.CN_media,GC.TAX.TOTL.GD.ZS_media,GC.TAX.YPKG.CN_media,GC.TAX.YPKG.RV.ZS_media,GC.TAX.YPKG.ZS_media,GC.XPN.COMP.CN_media,GC.XPN.COMP.ZS_media,GC.XPN.GSRV.CN_media,GC.XPN.GSRV.ZS_media,GC.XPN.INTP.CN_media,GC.XPN.INTP.RV.ZS_media,GC.XPN.INTP.ZS_media,GC.XPN.OTHR.CN_media,GC.XPN.OTHR.ZS_media,GC.XPN.TOTL.CN_media,GC.XPN.TOTL.GD.ZS_media,GC.XPN.TRFT.CN_media,GC.XPN.TRFT.ZS_media,GOV_WGI_CC_EST_media,GOV_WGI_CC_SC_media,GOV_WGI_GE_EST_media,GOV_WGI_GE_SC_media,GOV_WGI_PV_EST_media,GOV_WGI_PV_SC_media,GOV_WGI_RL_EST_media,GOV_WGI_RL_SC_media,GOV_WGI_RQ_EST_media,GOV_WGI_RQ_SC_media,GOV_WGI_VA_EST_media,GOV_WGI_VA_SC_media,IC.BUS.NDNS.ZS_media,IP.JRN.ARTC.SC_media,IP.PAT.NRES_media,IP.PAT.RESD_media,IQ.SPI.PIL1_media,IQ.SPI.PIL3_media,IS.AIR.PSGR_media,IS.SHP.GCNW.XQ_media,MS.MIL.XPND.GD.ZS_media,NE.CON.GOVT.CD_media,NE.CON.GOVT.CN_media,NE.CON.GOVT.KD_media,NE.CON.GOVT.KD.ZG_media,NE.CON.GOVT.KN_media,NE.CON.GOVT.ZS_media,NE.CON.PCAP.PP.CD_media,NE.CON.PCAP.PP.KD_media,NE.CON.PRVT.CD_media,NE.CON.PRVT.CN_media,NE.CON.PRVT.CN.AD_media,NE.CON.PRVT.KD_media,NE.CON.PRVT.KD.ZG_media,NE.CON.PRVT.KN_media,NE.CON.PRVT.PC.KD_media,NE.CON.PRVT.PC.KD.ZG_media,NE.CON.PRVT.PP.CD_media,NE.CON.PRVT.PP.KD_media,NE.CON.PRVT.ZS_media,NE.CON.TOTL.CD_media,NE.CON.TOTL.CN_media,NE.CON.TOTL.KD_media,NE.CON.TOTL.KD.ZG_media,NE.CON.TOTL.KN_media,NE.CON.TOTL.ZS_media,NE.DAB.DEFL.ZS_media,NE.DAB.TOTL.CD_media,NE.DAB.TOTL.CN_media,NE.DAB.TOTL.KD_media,NE.DAB.TOTL.KN_media,NE.DAB.TOTL.ZS_media,NE.EXP.GNFS.CD_media,NE.EXP.GNFS.CN_media,NE.EXP.GNFS.KD_media,NE.EXP.GNFS.KD.ZG_media,NE.EXP.GNFS.KN_media,NE.EXP.GNFS.ZS_media,NE.GDI.FTOT.CD_media,NE.GDI.FTOT.CN_media,NE.GDI.FTOT.KD_media,NE.GDI.FTOT.KD.ZG_media,NE.GDI.FTOT.KN_media,NE.GDI.FTOT.ZS_media,NE.GDI.STKB.CD_media,NE.GDI.STKB.CN_media,NE.GDI.TOTL.CD_media,NE.GDI.TOTL.CN_media,NE.GDI.TOTL.KD_media,NE.GDI.TOTL.KD.ZG_media,NE.GDI.TOTL.KN_media,NE.GDI.TOTL.ZS_media,NE.IMP.GNFS.CD_media,NE.IMP.GNFS.CN_media,NE.IMP.GNFS.KD_media,NE.IMP.GNFS.KD.ZG_media,NE.IMP.GNFS.KN_media,NE.IMP.GNFS.ZS_media,NE.RSB.GNFS.CD_media,NE.RSB.GNFS.CN_media,NE.RSB.GNFS.ZS_media,NE.TRD.GNFS.ZS_media,NV.AGR.EMPL.KD_media,NV.AGR.TOTL.CD_media,NV.AGR.TOTL.CN_media,NV.AGR.TOTL.KD_media,NV.AGR.TOTL.KD.ZG_media,NV.AGR.TOTL.KN_media,NV.AGR.TOTL.ZS_media,NV.IND.EMPL.KD_media,NV.IND.MANF.CD_media,NV.IND.MANF.CN_media,NV.IND.MANF.KD_media,NV.IND.MANF.KD.ZG_media,NV.IND.MANF.KN_media,NV.IND.MANF.ZS_media,NV.IND.TOTL.CD_media,NV.IND.TOTL.CN_media,NV.IND.TOTL.KD_media,NV.IND.TOTL.KD.ZG_media,NV.IND.TOTL.KN_media,NV.IND.TOTL.ZS_media,NV.SRV.EMPL.KD_media,NV.SRV.TOTL.CD_media,NV.SRV.TOTL.CN_media,NV.SRV.TOTL.KD_media,NV.SRV.TOTL.KD.ZG_media,NV.SRV.TOTL.KN_media,NV.SRV.TOTL.ZS_media,NY.ADJ.AEDU.CD_media,NY.ADJ.AEDU.GN.ZS_media,NY.ADJ.DCO2.CD_media,NY.ADJ.DCO2.GN.ZS_media,NY.ADJ.DFOR.CD_media,NY.ADJ.DFOR.GN.ZS_media,NY.ADJ.DKAP.CD_media,NY.ADJ.DKAP.GN.ZS_media,NY.ADJ.DMIN.CD_media,NY.ADJ.DMIN.GN.ZS_media,NY.ADJ.DNGY.CD_media,NY.ADJ.DNGY.GN.ZS_media,NY.ADJ.DPEM.CD_media,NY.ADJ.DPEM.GN.ZS_media,NY.ADJ.DRES.GN.ZS_media,NY.ADJ.ICTR.GN.ZS_media,NY.ADJ.NNAT.CD_media,NY.ADJ.NNAT.GN.ZS_media,NY.ADJ.NNTY.CD_media,NY.ADJ.NNTY.KD_media,NY.ADJ.NNTY.KD.ZG_media,NY.ADJ.NNTY.PC.CD_media,NY.ADJ.NNTY.PC.KD_media,NY.ADJ.NNTY.PC.KD.ZG_media,NY.ADJ.SVNG.CD_media,NY.ADJ.SVNG.GN.ZS_media,NY.ADJ.SVNX.CD_media,NY.ADJ.SVNX.GN.ZS_media,NY.GDP.COAL.RT.ZS_media,NY.GDP.DEFL.ZS_media,NY.GDP.DEFL.ZS.AD_media,NY.GDP.MINR.RT.ZS_media,NY.GDP.MKTP.CD_media,NY.GDP.MKTP.KD_media,NY.GDP.MKTP.KD.ZG_media,NY.GDP.MKTP.PP.CD_media,NY.GDP.MKTP.PP.KD_media,NY.GDP.NGAS.RT.ZS_media,NY.GDP.PCAP.CD_media,NY.GDP.PCAP.KD_media,NY.GDP.PCAP.KD.ZG_media,NY.GDP.PCAP.PP.CD_media,NY.GDP.PCAP.PP.KD_media,NY.GDP.PETR.RT.ZS_media,NY.GDP.TOTL.RT.ZS_media,NY.GDS.TOTL.CD_media,NY.GDS.TOTL.CN_media,NY.GDS.TOTL.ZS_media,NY.GDY.TOTL.KN_media,NY.GNP.ATLS.CD_media,NY.GNP.MKTP.CD_media,NY.GNP.MKTP.CN_media,NY.GNP.MKTP.CN.AD_media,NY.GNP.MKTP.KD_media,NY.GNP.MKTP.KD.ZG_media,NY.GNP.MKTP.KN_media,NY.GNP.MKTP.PP.CD_media,NY.GNP.MKTP.PP.KD_media,NY.GNP.PCAP.CD_media,NY.GNP.PCAP.CN_media,NY.GNP.PCAP.KD_media,NY.GNP.PCAP.KD.ZG_media,NY.GNP.PCAP.KN_media,NY.GNP.PCAP.PP.CD_media,NY.GNP.PCAP.PP.KD_media,NY.GNS.ICTR.CD_media,NY.GNS.ICTR.CN_media,NY.GNS.ICTR.GN.ZS_media,NY.GNS.ICTR.ZS_media,NY.TRF.NCTR.CN_media,PA.NUS.ATLS_media,PA.NUS.FCRF_media,PA.NUS.GDP.PLI_media,PA.NUS.PPP_media,PA.NUS.PRVT.PLI_media,PA.NUS.PRVT.PP_media,SE.COM.DURS_media,SE.ENR.PRIM.FM.ZS_media,SE.ENR.PRSC.FM.ZS_media,SE.ENR.SECO.FM.ZS_media,SE.ENR.TERT.FM.ZS_media,SE.PRM.AGES_media,SE.PRM.CMPT.FE.ZS_media,SE.PRM.CMPT.MA.ZS_media,SE.PRM.CMPT.ZS_media,SE.PRM.DURS_media,SE.PRM.ENRL_media,SE.PRM.ENRL.FE.ZS_media,SE.PRM.ENRL.TC.ZS_media,SE.PRM.ENRR_media,SE.PRM.ENRR.FE_media,SE.PRM.ENRR.MA_media,SE.PRM.GINT.FE.ZS_media,SE.PRM.GINT.MA.ZS_media,SE.PRM.GINT.ZS_media,SE.PRM.NENR_media,SE.PRM.OENR.FE.ZS_media,SE.PRM.OENR.MA.ZS_media,SE.PRM.OENR.ZS_media,SE.PRM.PRIV.ZS_media,SE.PRM.REPT.FE.ZS_media,SE.PRM.REPT.MA.ZS_media,SE.PRM.REPT.ZS_media,SE.PRM.TCHR_media,SE.PRM.TCHR.FE.ZS_media,SE.PRM.UNER_media,SE.PRM.UNER.ZS_media,SE.SEC.AGES_media,SE.SEC.CMPT.LO.FE.ZS_media,SE.SEC.CMPT.LO.MA.ZS_media,SE.SEC.CMPT.LO.ZS_media,SE.SEC.DURS_media,SE.SEC.ENRL_media,SE.SEC.ENRL.FE.ZS_media,SE.SEC.ENRL.GC_media,SE.SEC.ENRL.GC.FE.ZS_media,SE.SEC.ENRL.VO_media,SE.SEC.ENRR_media,SE.SEC.ENRR.FE_media,SE.SEC.ENRR.MA_media,SE.SEC.PRIV.ZS_media,SE.TER.ENRR_media,SE.TER.ENRR.FE_media,SE.TER.ENRR.MA_media,SE.XPD.TOTL.GB.ZS_media,SE.XPD.TOTL.GD.ZS_media,SG.GEN.PARL.ZS_media,SH.DYN.MORT_media,SH.DYN.MORT.FE_media,SH.DYN.MORT.MA_media,SH.DYN.NMRT_media,SH.H2O.BASW.RU.ZS_media,SH.H2O.BASW.UR.ZS_media,SH.H2O.BASW.ZS_media,SH.H2O.SMDW.ZS_media,SH.HIV.1524.FE.ZS_media,SH.HIV.1524.MA.ZS_media,SH.HIV.ARTC.ZS_media,SH.HIV.INCD_media,SH.HIV.INCD.TL_media,SH.HIV.INCD.TL.P3_media,SH.HIV.INCD.YG_media,SH.HIV.INCD.YG.P3_media,SH.HIV.INCD.ZS_media,SH.MED.BEDS.ZS_media,SH.MED.NUMW.P3_media,SH.MED.PHYS.ZS_media,SH.STA.BASS.RU.ZS_media,SH.STA.BASS.UR.ZS_media,SH.STA.BASS.ZS_media,SH.STA.BRTW.ZS_media,SH.STA.MMRT_media,SH.STA.ODFC.RU.ZS_media,SH.STA.ODFC.UR.ZS_media,SH.STA.ODFC.ZS_media,SH.STA.OWGH.ME.FE.ZS_media,SH.STA.OWGH.ME.MA.ZS_media,SH.STA.OWGH.ME.ZS_media,SH.STA.POIS.P5.MA_media,SH.STA.SMSS.ZS_media,SH.STA.STNT.ME.FE.ZS_media,SH.STA.STNT.ME.MA.ZS_media,SH.STA.STNT.ME.ZS_media,SH.STA.SUIC.FE.P5_media,SH.TBS.CURE.ZS_media,SH.TBS.DTEC.ZS_media,SH.TBS.INCD_media,SH.XPD.CHEX.GD.ZS_media,SH.XPD.CHEX.PC.CD_media,SH.XPD.CHEX.PP.CD_media,SH.XPD.EHEX.CH.ZS_media,SH.XPD.EHEX.PC.CD_media,SH.XPD.EHEX.PP.CD_media,SH.XPD.GHED.CH.ZS_media,SH.XPD.GHED.GD.ZS_media,SH.XPD.GHED.GE.ZS_media,SH.XPD.GHED.PC.CD_media,SH.XPD.GHED.PP.CD_media,SH.XPD.OOPC.CH.ZS_media,SH.XPD.OOPC.PC.CD_media,SH.XPD.OOPC.PP.CD_media,SH.XPD.PVTD.CH.ZS_media,SH.XPD.PVTD.PC.CD_media,SH.XPD.PVTD.PP.CD_media,SL.AGR.EMPL.FE.ZS_media,SL.AGR.EMPL.MA.ZS_media,SL.AGR.EMPL.ZS_media,SL.EMP.1524.SP.FE.ZS_media,SL.EMP.1524.SP.MA.ZS_media,SL.EMP.1524.SP.ZS_media,SL.EMP.MPYR.FE.ZS_media,SL.EMP.MPYR.MA.ZS_media,SL.EMP.MPYR.ZS_media,SL.EMP.SELF.FE.ZS_media,SL.EMP.SELF.MA.ZS_media,SL.EMP.SELF.ZS_media,SL.EMP.TOTL.SP.FE.ZS_media,SL.EMP.TOTL.SP.MA.ZS_media,SL.EMP.TOTL.SP.ZS_media,SL.EMP.VULN.FE.ZS_media,SL.EMP.VULN.MA.ZS_media,SL.EMP.VULN.ZS_media,SL.EMP.WORK.FE.ZS_media,SL.EMP.WORK.MA.ZS_media,SL.EMP.WORK.ZS_media,SL.GDP.PCAP.EM.KD_media,SL.IND.EMPL.FE.ZS_media,SL.IND.EMPL.MA.ZS_media,SL.IND.EMPL.ZS_media,SL.SRV.EMPL.FE.ZS_media,SL.SRV.EMPL.MA.ZS_media,SL.SRV.EMPL.ZS_media,SL.TLF.ACTI.1524.FE.ZS_media,SL.TLF.ACTI.1524.MA.ZS_media,SL.TLF.ACTI.1524.ZS_media,SL.TLF.ACTI.FE.ZS_media,SL.TLF.ACTI.MA.ZS_media,SL.TLF.ACTI.ZS_media,SL.TLF.CACT.FE.ZS_media,SL.TLF.CACT.FM.ZS_media,SL.TLF.CACT.MA.ZS_media,SL.TLF.CACT.NE.ZS_media,SL.TLF.CACT.ZS_media,SL.TLF.TOTL.FE.ZS_media,SL.TLF.TOTL.IN_media,SL.UEM.1524.FE.ZS_media,SL.UEM.1524.MA.ZS_media,SL.UEM.1524.ZS_media,SL.UEM.NEET.FE.ME.ZS_media,SL.UEM.NEET.MA.ME.ZS_media,SL.UEM.NEET.ME.ZS_media,SL.UEM.TOTL.FE.NE.ZS_media,SL.UEM.TOTL.FE.ZS_media,SL.UEM.TOTL.MA.NE.ZS_media,SL.UEM.TOTL.MA.ZS_media,SL.UEM.TOTL.NE.ZS_media,SL.UEM.TOTL.ZS_media,SM.POP.ASYS.EA_media,SM.POP.ASYS.EO_media,SM.POP.NETM_media,SM.POP.RHCR.EA_media,SM.POP.RHCR.EO_media,SN.ITK.DEFC.ZS_media,SP.ADO.TFRT_media,SP.DYN.AMRT.FE_media,SP.DYN.AMRT.MA_media,SP.DYN.CBRT.IN_media,SP.DYN.CDRT.IN_media,SP.DYN.IMRT.FE.IN_media,SP.DYN.IMRT.IN_media,SP.DYN.IMRT.MA.IN_media,SP.DYN.LE00.FE.IN_media,SP.DYN.LE00.IN_media,SP.DYN.LE00.MA.IN_media,SP.DYN.TFRT.IN_media,SP.DYN.TO65.FE.ZS_media,SP.DYN.TO65.MA.ZS_media,SP.POP.0004.FE.5Y_media,SP.POP.0004.MA.5Y_media,SP.POP.0014.FE.IN_media,SP.POP.0014.FE.ZS_media,SP.POP.0014.MA.IN_media,SP.POP.0014.MA.ZS_media,SP.POP.0014.TO_media,SP.POP.0014.TO.ZS_media,SP.POP.0509.FE.5Y_media,SP.POP.0509.MA.5Y_media,SP.POP.1014.FE.5Y_media,SP.POP.1014.MA.5Y_media,SP.POP.1519.FE.5Y_media,SP.POP.1519.MA.5Y_media,SP.POP.1564.FE.IN_media,SP.POP.1564.FE.ZS_media,SP.POP.1564.MA.IN_media,SP.POP.1564.MA.ZS_media,SP.POP.1564.TO_media,SP.POP.1564.TO.ZS_media,SP.POP.2024.FE.5Y_media,SP.POP.2024.MA.5Y_media,SP.POP.2529.FE.5Y_media,SP.POP.2529.MA.5Y_media,SP.POP.3034.FE.5Y_media,SP.POP.3034.MA.5Y_media,SP.POP.3539.FE.5Y_media,SP.POP.3539.MA.5Y_media,SP.POP.4044.FE.5Y_media,SP.POP.4044.MA.5Y_media,SP.POP.4549.FE.5Y_media,SP.POP.4549.MA.5Y_media,SP.POP.5054.FE.5Y_media,SP.POP.5054.MA.5Y_media,SP.POP.5559.FE.5Y_media,SP.POP.5559.MA.5Y_media,SP.POP.6064.FE.5Y_media,SP.POP.6064.MA.5Y_media,SP.POP.6569.FE.5Y_media,SP.POP.6569.MA.5Y_media,SP.POP.65UP.FE.IN_media,SP.POP.65UP.FE.ZS_media,SP.POP.65UP.MA.IN_media,SP.POP.65UP.MA.ZS_media,SP.POP.65UP.TO_media,SP.POP.65UP.TO.ZS_media,SP.POP.7074.FE.5Y_media,SP.POP.7074.MA.5Y_media,SP.POP.7579.FE.5Y_media,SP.POP.7579.MA.5Y_media,SP.POP.80UP.FE.5Y_media,SP.POP.80UP.MA.5Y_media,SP.POP.BRTH.MF_media,SP.POP.DPND_media,SP.POP.DPND.OL_media,SP.POP.DPND.YG_media,SP.POP.GROW_media,SP.POP.TOTL_media,SP.POP.TOTL.FE.IN_media,SP.POP.TOTL.FE.ZS_media,SP.POP.TOTL.MA.IN_media,SP.POP.TOTL.MA.ZS_media,SP.RUR.TOTL_media,SP.RUR.TOTL.ZG_media,SP.RUR.TOTL.ZS_media,SP.URB.GROW_media,SP.URB.TOTL_media,SP.URB.TOTL.IN.ZS_media,ST.INT.ARVL_media,ST.INT.RCPT.CD_media,ST.INT.RCPT.XP.ZS_media,TG.VAL.TOTL.GD.ZS_media,TM.TAX.MANF.BC.ZS_media,TM.TAX.MANF.BR.ZS_media,TM.TAX.MANF.SM.AR.ZS_media,TM.TAX.MANF.SM.FN.ZS_media,TM.TAX.MANF.WM.AR.ZS_media,TM.TAX.MANF.WM.FN.ZS_media,TM.TAX.MRCH.BC.ZS_media,TM.TAX.MRCH.BR.ZS_media,TM.TAX.MRCH.SM.AR.ZS_media,TM.TAX.MRCH.SM.FN.ZS_media,TM.TAX.MRCH.WM.AR.ZS_media,TM.TAX.MRCH.WM.FN.ZS_media,TM.VAL.AGRI.ZS.UN_media,TM.VAL.FOOD.ZS.UN_media,TM.VAL.FUEL.ZS.UN_media,TM.VAL.ICTG.ZS.UN_media,TM.VAL.INSF.ZS.WT_media,TM.VAL.MANF.ZS.UN_media,TM.VAL.MMTL.ZS.UN_media,TM.VAL.MRCH.AL.ZS_media,TM.VAL.MRCH.CD.WT_media,TM.VAL.MRCH.HI.ZS_media,TM.VAL.MRCH.OR.ZS_media,TM.VAL.MRCH.R1.ZS_media,TM.VAL.MRCH.R2.ZS_media,TM.VAL.MRCH.R3.ZS_media,TM.VAL.MRCH.R4.ZS_media,TM.VAL.MRCH.R5.ZS_media,TM.VAL.MRCH.R6.ZS_media,TM.VAL.MRCH.RS.ZS_media,TM.VAL.MRCH.WL.CD_media,TM.VAL.MRCH.WR.ZS_media,TM.VAL.MRCH.XD.WD_media,TM.VAL.OTHR.ZS.WT_media,TM.VAL.SERV.CD.WT_media,TM.VAL.TRAN.ZS.WT_media,TM.VAL.TRVL.ZS.WT_media,TT.PRI.MRCH.XD.WD_media,TX.MNF.TECH.ZS.UN_media,TX.VAL.AGRI.ZS.UN_media,TX.VAL.FOOD.ZS.UN_media,TX.VAL.FUEL.ZS.UN_media,TX.VAL.ICTG.ZS.UN_media,TX.VAL.INSF.ZS.WT_media,TX.VAL.MANF.ZS.UN_media,TX.VAL.MMTL.ZS.UN_media,TX.VAL.MRCH.AL.ZS_media,TX.VAL.MRCH.CD.WT_media,TX.VAL.MRCH.HI.ZS_media,TX.VAL.MRCH.OR.ZS_media,TX.VAL.MRCH.R1.ZS_media,TX.VAL.MRCH.R2.ZS_media,TX.VAL.MRCH.R3.ZS_media,TX.VAL.MRCH.R4.ZS_media,TX.VAL.MRCH.R5.ZS_media,TX.VAL.MRCH.R6.ZS_media,TX.VAL.MRCH.RS.ZS_media,TX.VAL.MRCH.WL.CD_media,TX.VAL.MRCH.WR.ZS_media,TX.VAL.MRCH.XD.WD_media,TX.VAL.OTHR.ZS.WT_media,TX.VAL.SERV.CD.WT_media,TX.VAL.TRAN.ZS.WT_media,TX.VAL.TRVL.ZS.WT_media,hh_market_concentration_media,v2x_clphy_media,v2x_cspart_media,v2x_delibdem_stock_media,v2x_diagacc_media,v2x_divparctrl_media,v2x_egaldem_stock_media,v2x_elecreg_media,v2x_electoral_integrity_media,v2x_ex_confidence_media,v2x_ex_direlect_media,v2x_ex_hereditary_media,v2x_ex_military_media,v2x_ex_party_media,v2x_execorr_media,v2x_feduni_media,v2x_gencl_media,v2x_gencs_media,v2x_genpp_media,v2x_horacc_media,v2x_hosinter_media,v2x_jucon_media,v2x_libdem_stock_media,v2x_partipdem_stock_media,v2x_polyarchy_stock_media,v2x_pubcorr_media,v2x_regime_amb_media,v2x_suffr_media,v2xca_academ_media,v2xcl_acjst_media,v2xcl_disc_media,v2xcl_dmove_media,v2xcl_prpty_media,v2xcl_slave_media,v2xcs_ccsi_media,v2xdd_dd_media,v2xdd_i_ci_media,v2xdd_i_or_media,v2xdd_i_pl_media,v2xdd_i_rf_media,v2xdl_delib_media,v2xed_ed_cent_media,v2xed_ed_con_media,v2xed_ed_ctag_media,v2xed_ed_dmcon_media,v2xed_ed_poed_media,v2xed_ed_ptcon_media,v2xed_ptcon_media,v2xedvd_me_cent_media,v2xedvd_me_ctag_media,v2xeg_eqaccess_media,v2xeg_eqdr_media,v2xel_elecparl_media,v2xel_elecpres_media,v2xel_locelec_media,v2xel_regelec_media,v2xex_elecleg_media,v2xlg_legcon_media,v2xlg_leginter_media,v2xme_altinf_media,v2xnp_pres_media,v2xnp_regcorr_media,v2xpe_exlecon_media,v2xpe_exlgender_media,v2xpe_exlgeo_media,v2xpe_exlpol_media,v2xpe_exlsocgr_media,v2xps_party_media,AG.LND.TOTL.K2_tendencia,BG.GSR.NFSV.GD.ZS_tendencia,BM.GSR.CMCP.ZS_tendencia,BM.GSR.FCTY.CD_tendencia,BM.GSR.GNFS.CD_tendencia,BM.GSR.INSF.ZS_tendencia,BM.GSR.MRCH.CD_tendencia,BM.GSR.NFSV.CD_tendencia,BM.GSR.ROYL.CD_tendencia,BM.GSR.TOTL.CD_tendencia,BM.GSR.TRAN.ZS_tendencia,BM.GSR.TRVL.ZS_tendencia,BM.KLT.DINV.CD.WD_tendencia,BM.KLT.DINV.WD.GD.ZS_tendencia,BM.TRF.PRVT.CD_tendencia,BM.TRF.PWKR.CD.DT_tendencia,BN.CAB.XOKA.CD_tendencia,BN.CAB.XOKA.GD.ZS_tendencia,BN.FIN.TOTL.CD_tendencia,BN.GSR.FCTY.CD_tendencia,BN.GSR.GNFS.CD_tendencia,BN.GSR.MRCH.CD_tendencia,BN.KAC.EOMS.CD_tendencia,BN.KLT.DINV.CD_tendencia,BN.KLT.PTXL.CD_tendencia,BN.RES.INCL.CD_tendencia,BN.TRF.CURR.CD_tendencia,BN.TRF.KOGT.CD_tendencia,BX.GRT.EXTA.CD.WD_tendencia,BX.GRT.TECH.CD.WD_tendencia,BX.GSR.CCIS.CD_tendencia,BX.GSR.CCIS.ZS_tendencia,BX.GSR.CMCP.ZS_tendencia,BX.GSR.FCTY.CD_tendencia,BX.GSR.GNFS.CD_tendencia,BX.GSR.INSF.ZS_tendencia,BX.GSR.MRCH.CD_tendencia,BX.GSR.NFSV.CD_tendencia,BX.GSR.ROYL.CD_tendencia,BX.GSR.TOTL.CD_tendencia,BX.GSR.TRAN.ZS_tendencia,BX.GSR.TRVL.ZS_tendencia,BX.KLT.DINV.CD.WD_tendencia,BX.KLT.DINV.WD.GD.ZS_tendencia,BX.PEF.TOTL.CD.WD_tendencia,BX.TRF.CURR.CD_tendencia,BX.TRF.PWKR.CD_tendencia,BX.TRF.PWKR.CD.DT_tendencia,BX.TRF.PWKR.DT.GD.ZS_tendencia,DC.DAC.TOTL.CD_tendencia,DT.ODA.ODAT.CD_tendencia,DT.ODA.ODAT.GN.ZS_tendencia,DT.ODA.ODAT.PC.ZS_tendencia,EG.ELC.ACCS.RU.ZS_tendencia,EG.ELC.ACCS.UR.ZS_tendencia,EG.ELC.ACCS.ZS_tendencia,EG.IMP.CONS.ZS_tendencia,EG.USE.ELEC.KH.PC_tendencia,EG.USE.PCAP.KG.OE_tendencia,EN.POP.DNST_tendencia,FB.ATM.TOTL.P5_tendencia,FB.CBK.BRCH.P5_tendencia,FD.AST.PRVT.GD.ZS_tendencia,FD.RES.LIQU.AS.ZS_tendencia,FI.RES.TOTL.CD_tendencia,FI.RES.TOTL.MO_tendencia,FI.RES.XGLD.CD_tendencia,FM.AST.CGOV.ZG.M3_tendencia,FM.AST.DOMO.ZG.M3_tendencia,FM.AST.DOMS.CN_tendencia,FM.AST.NFRG.CN_tendencia,FM.AST.PRVT.GD.ZS_tendencia,FM.AST.PRVT.ZG.M3_tendencia,FM.LBL.BMNY.CN_tendencia,FM.LBL.BMNY.GD.ZS_tendencia,FM.LBL.BMNY.IR.ZS_tendencia,FM.LBL.BMNY.ZG_tendencia,FR.INR.DPST_tendencia,FR.INR.LEND_tendencia,FR.INR.RINR_tendencia,FS.AST.CGOV.GD.ZS_tendencia,FS.AST.PRVT.GD.ZS_tendencia,GB.XPD.RSDV.GD.ZS_tendencia,GC.NFN.TOTL.GD.ZS_tendencia,GC.NLD.TOTL.GD.ZS_tendencia,GC.REV.GOTR.CN_tendencia,GC.REV.GOTR.ZS_tendencia,GC.REV.XGRT.CN_tendencia,GC.REV.XGRT.GD.ZS_tendencia,GC.TAX.GSRV.CN_tendencia,GC.TAX.GSRV.RV.ZS_tendencia,GC.TAX.GSRV.VA.ZS_tendencia,GC.TAX.IMPT.CN_tendencia,GC.TAX.IMPT.ZS_tendencia,GC.TAX.INTT.CN_tendencia,GC.TAX.INTT.RV.ZS_tendencia,GC.TAX.OTHR.CN_tendencia,GC.TAX.OTHR.RV.ZS_tendencia,GC.TAX.TOTL.CN_tendencia,GC.TAX.TOTL.GD.ZS_tendencia,GC.TAX.YPKG.CN_tendencia,GC.TAX.YPKG.RV.ZS_tendencia,GC.TAX.YPKG.ZS_tendencia,GC.XPN.COMP.CN_tendencia,GC.XPN.COMP.ZS_tendencia,GC.XPN.GSRV.CN_tendencia,GC.XPN.GSRV.ZS_tendencia,GC.XPN.INTP.CN_tendencia,GC.XPN.INTP.RV.ZS_tendencia,GC.XPN.INTP.ZS_tendencia,GC.XPN.OTHR.CN_tendencia,GC.XPN.OTHR.ZS_tendencia,GC.XPN.TOTL.CN_tendencia,GC.XPN.TOTL.GD.ZS_tendencia,GC.XPN.TRFT.CN_tendencia,GC.XPN.TRFT.ZS_tendencia,GOV_WGI_CC_EST_tendencia,GOV_WGI_CC_SC_tendencia,GOV_WGI_GE_EST_tendencia,GOV_WGI_GE_SC_tendencia,GOV_WGI_PV_EST_tendencia,GOV_WGI_PV_SC_tendencia,GOV_WGI_RL_EST_tendencia,GOV_WGI_RL_SC_tendencia,GOV_WGI_RQ_EST_tendencia,GOV_WGI_RQ_SC_tendencia,GOV_WGI_VA_EST_tendencia,GOV_WGI_VA_SC_tendencia,IC.BUS.NDNS.ZS_tendencia,IP.JRN.ARTC.SC_tendencia,IP.PAT.NRES_tendencia,IP.PAT.RESD_tendencia,IQ.SPI.PIL1_tendencia,IQ.SPI.PIL3_tendencia,IS.AIR.PSGR_tendencia,IS.SHP.GCNW.XQ_tendencia,MS.MIL.XPND.GD.ZS_tendencia,NE.CON.GOVT.CD_tendencia,NE.CON.GOVT.CN_tendencia,NE.CON.GOVT.KD_tendencia,NE.CON.GOVT.KD.ZG_tendencia,NE.CON.GOVT.KN_tendencia,NE.CON.GOVT.ZS_tendencia,NE.CON.PCAP.PP.CD_tendencia,NE.CON.PCAP.PP.KD_tendencia,NE.CON.PRVT.CD_tendencia,NE.CON.PRVT.CN_tendencia,NE.CON.PRVT.CN.AD_tendencia,NE.CON.PRVT.KD_tendencia,NE.CON.PRVT.KD.ZG_tendencia,NE.CON.PRVT.KN_tendencia,NE.CON.PRVT.PC.KD_tendencia,NE.CON.PRVT.PC.KD.ZG_tendencia,NE.CON.PRVT.PP.CD_tendencia,NE.CON.PRVT.PP.KD_tendencia,NE.CON.PRVT.ZS_tendencia,NE.CON.TOTL.CD_tendencia,NE.CON.TOTL.CN_tendencia,NE.CON.TOTL.KD_tendencia,NE.CON.TOTL.KD.ZG_tendencia,NE.CON.TOTL.KN_tendencia,NE.CON.TOTL.ZS_tendencia,NE.DAB.DEFL.ZS_tendencia,NE.DAB.TOTL.CD_tendencia,NE.DAB.TOTL.CN_tendencia,NE.DAB.TOTL.KD_tendencia,NE.DAB.TOTL.KN_tendencia,NE.DAB.TOTL.ZS_tendencia,NE.EXP.GNFS.CD_tendencia,NE.EXP.GNFS.CN_tendencia,NE.EXP.GNFS.KD_tendencia,NE.EXP.GNFS.KD.ZG_tendencia,NE.EXP.GNFS.KN_tendencia,NE.EXP.GNFS.ZS_tendencia,NE.GDI.FTOT.CD_tendencia,NE.GDI.FTOT.CN_tendencia,NE.GDI.FTOT.KD_tendencia,NE.GDI.FTOT.KD.ZG_tendencia,NE.GDI.FTOT.KN_tendencia,NE.GDI.FTOT.ZS_tendencia,NE.GDI.STKB.CD_tendencia,NE.GDI.STKB.CN_tendencia,NE.GDI.TOTL.CD_tendencia,NE.GDI.TOTL.CN_tendencia,NE.GDI.TOTL.KD

## 2. Vamos a ver cómo se distribuyen los valores faltantes

In [7]:
missingness_pais_completo = (
    df_pais_features.isna().mean(axis=1) * 100
).round(1).sort_values(ascending=True)

df_missingness_pais_ordenado = missingness_pais_completo.reset_index()
df_missingness_pais_ordenado.columns = ["pais", "pct_missingness"]
df_missingness_pais_ordenado["orden"] = range(1, len(df_missingness_pais_ordenado) + 1)

df_regiones = pd.read_excel("df_regiones_miembros_onu.xlsx")  # ajustar ruta si corresponde

df_missingness_pais_ordenado = df_missingness_pais_ordenado.merge(
    df_regiones[["ISO-alpha3", "Member State"]],
    left_on="pais", right_on="ISO-alpha3", how="left"
).drop(columns="ISO-alpha3").rename(columns={"Member State": "nombre_pais"})

df_missingness_pais_ordenado = df_missingness_pais_ordenado[["pais", "nombre_pais", "pct_missingness", "orden"]]

print(f"N paises: {len(df_missingness_pais_ordenado)}")
df_missingness_pais_ordenado.tail(50)

N paises: 193

    pais                            nombre_pais  pct_missingness  orden
143  YEM                                  Yemen             10.2    144
144  GNB                          Guinea-Bissau             10.3    145
145  DJI                               Djibouti             11.5    146
146  MWI                                 Malawi             11.5    147
147  STP                  Sao Tome and Principe             11.6    148
148  GUY                                 Guyana             11.9    149
149  BLZ                                 Belize             12.0    150
150  SYC                             Seychelles             12.4    151
151  SYR                   Syrian Arab Republic             12.6    152
152  SUR                               Suriname             13.0    153
153  MMR                                Myanmar             13.2    154
154  VEN     Venezuela (Bolivarian Republic of)             13.3    155
155  WSM                                  Samoa             13.3    156
156  JAM                                Jamaica             13.3    157
157  TTO                    Trinidad and Tobago             13.7    158
158  AFG                            Afghanistan             13.7    159
159  CAF               Central African Republic             13.8    160
160  ARE                   United Arab Emirates             14.5    161
161  TON                                  Tonga             14.5    162
162  LBY                                  Libya             14.7    163
163  HTI                                  Haiti             15.3    164
164  BRB                               Barbados             15.5    165
165  BHS                          Bahamas (The)             17.1    166
166  NGA                                Nigeria             18.0    167
167  TCD                                   Chad             18.2    168
168  GNQ                      Equatorial Guinea             18.7    169
169  BRN                      Brunei Darussalam             19.3    170
170  CUB                                   Cuba             22.2    171
171  ERI                                Eritrea             23.4    172
172  LBR                                Liberia             23.8    173
173  LCA                            Saint Lucia             24.3    174
174  SSD                            South Sudan             24.9    175
175  VCT       Saint Vincent and the Grenadines             25.6    176
176  KIR                               Kiribati             28.6    177
177  SOM                                Somalia             31.8    178
178  MHL                       Marshall Islands             33.0    179
179  PLW                                  Palau             33.8    180
180  TKM                           Turkmenistan             33.9    181
181  KNA                  Saint Kitts and Nevis             36.4    182
182  ATG                    Antigua and Barbuda             37.2    183
183  DMA                               Dominica             39.1    184
184  GRD                                Grenada             41.1    185
185  FSM       Micronesia (Federated States of)             41.7    186
186  SMR                             San Marino             44.4    187
187  NRU                                  Nauru             47.2    188
188  TUV                                 Tuvalu             50.1    189
189  PRK  Democratic People's Republic of Korea             55.2    190
190  AND                                Andorra             60.3    191
191  LIE                          Liechtenstein             67.4    192
192  MCO                                 Monaco             70.9    193

In [8]:
fig_bar = px.bar(
    df_missingness_pais_ordenado, x="orden", y="pct_missingness",
    hover_data=["pais"],
    title="Missingness por país, ordenado de menor a mayor (193 países)",
    labels={"orden": "Países ordenados (de menor a mayor missingness)", "pct_missingness": "% de features faltantes"}
)
fig_bar.show()

In [9]:
fig_line = px.line(
    df_missingness_pais_ordenado, x="orden", y="pct_missingness",
    markers=False,
    title="Curva de missingness por país, ordenada (193 países)",
    labels={"orden": "Países ordenados (de menor a mayor missingness)", "pct_missingness": "% de features faltantes"}
)
fig_line.show()

In [10]:
umbrales_pais = list(range(0, 81, 3))

n_excluidos_por_umbral = [
    (missingness_pais_completo > u).sum()
    for u in umbrales_pais
]

df_sensibilidad_pais = pd.DataFrame({
    "umbral": umbrales_pais,
    "n_excluidos": n_excluidos_por_umbral,
})

fig_sens_pais = px.line(
    df_sensibilidad_pais, x="umbral", y="n_excluidos", markers=True,
    title="Sensibilidad: países excluidos según umbral de missingness",
    labels={"umbral": "Umbral de missingness por país (%)", "n_excluidos": "N países excluidos"}
)
fig_sens_pais.show()

In [11]:
# Tabla de saltos (gaps) entre países consecutivos en la cola alta, para ubicar el valle real
cola_alta = df_missingness_pais_ordenado.tail(30).copy()
cola_alta["salto"] = cola_alta["pct_missingness"].diff()
cola_alta.sort_values("salto", ascending=False).head(10)

    pais                            nombre_pais  pct_missingness  orden  salto
191  LIE                          Liechtenstein             67.4    192    7.1
189  PRK  Democratic People's Republic of Korea             55.2    190    5.1
190  AND                                Andorra             60.3    191    5.1
192  MCO                                 Monaco             70.9    193    3.5
177  SOM                                Somalia             31.8    178    3.2
176  KIR                               Kiribati             28.6    177    3.0
188  TUV                                 Tuvalu             50.1    189    2.9
170  CUB                                   Cuba             22.2    171    2.9
187  NRU                                  Nauru             47.2    188    2.8
186  SMR                             San Marino             44.4    187    2.7

Boxplot de missingness por país (con detección de outliers)

In [12]:
Q1 = missingness_pais_completo.quantile(0.25)
Q3 = missingness_pais_completo.quantile(0.75)
IQR = Q3 - Q1
umbral_tukey = Q3 + 1.5 * IQR

print(f"Q1: {Q1:.1f}%  |  Q3: {Q3:.1f}%  |  IQR: {IQR:.1f}")
print(f"Umbral de outlier (Tukey, Q3 + 1.5*IQR): {umbral_tukey:.1f}%")

paises_outlier_tukey = missingness_pais_completo[missingness_pais_completo > umbral_tukey]
print(f"\nPaises outlier segun Tukey: {len(paises_outlier_tukey)}")
print(paises_outlier_tukey)

Q1: 1.7%  |  Q3: 10.3%  |  IQR: 8.6
Umbral de outlier (Tukey, Q3 + 1.5*IQR): 23.2%

Paises outlier segun Tukey: 22
ISO-alpha3
ERI    23.4
LBR    23.8
LCA    24.3
SSD    24.9
VCT    25.6
KIR    28.6
SOM    31.8
MHL    33.0
PLW    33.8
TKM    33.9
KNA    36.4
ATG    37.2
DMA    39.1
GRD    41.1
FSM    41.7
SMR    44.4
NRU    47.2
TUV    50.1
PRK    55.2
AND    60.3
LIE    67.4
MCO    70.9
dtype: float64

In [13]:
fig_box_pais = px.box(
    y=missingness_pais_completo, points="all",
    title="Distribución de missingness por país (193 países) — detección de outliers",
    labels={"y": "% de features faltantes"}
)
fig_box_pais.show()

## 3. Exclusión de países con alta missingness (>40%)
Se excluyen los 9 países identificados (microestados extremos + Corea del Norte), según la decisión ya justificada.

In [14]:
paises_excluidos_missingness = ["MCO", "LIE", "AND", "PRK", "TUV", "NRU", "SMR", "FSM", "GRD"]

df_pais_features_reducido = df_pais_features.drop(index=paises_excluidos_missingness, errors="ignore")

print(f"Paises excluidos: {len(paises_excluidos_missingness)}")
print(f"Shape original: {df_pais_features.shape}")
print(f"Shape tras exclusion: {df_pais_features_reducido.shape}")

Paises excluidos: 9
Shape original: (193, 2058)
Shape tras exclusion: (184, 2058)

## 4. Missingness remanente (184 países)
Panorama real sobre el que se decide la imputación.

In [15]:
missingness_col_post = (df_pais_features_reducido.isna().mean() * 100).round(1)
missingness_pais_post = (df_pais_features_reducido.isna().mean(axis=1) * 100).round(1)

print(f"Missingness global promedio (184 paises): {missingness_col_post.mean():.2f}%")
print("\nTop 10 columnas con mayor missingness:")
print(missingness_col_post.sort_values(ascending=False).head(10))

Missingness global promedio (184 paises): 6.81%

Top 10 columnas con mayor missingness:
GB.XPD.RSDV.GD.ZS_tendencia      40.2
GB.XPD.RSDV.GD.ZS_volatilidad    40.2
IP.PAT.RESD_tendencia            34.2
IP.PAT.RESD_volatilidad          34.2
SH.H2O.SMDW.ZS_media             29.9
SH.H2O.SMDW.ZS_volatilidad       29.9
SH.H2O.SMDW.ZS_tendencia         29.9
BX.GSR.ROYL.CD_volatilidad       29.3
BX.GSR.ROYL.CD_tendencia         29.3
GC.TAX.IMPT.ZS_tendencia         28.8
dtype: float64

## 5. Imputación
Se estandarizan las variables y luego se imputa con KNN sobre la matriz ya estandarizada — así la distancia entre países no queda dominada por variables en escalas más grandes (USD, etc.).Se usa un  método KNN con  k=5 .

In [16]:
from sklearn.impute import KNNImputer
from sklearn.metrics import mean_squared_error

col_means = df_pais_features_reducido.mean(skipna=True)
col_stds = df_pais_features_reducido.std(skipna=True)
X_std = (df_pais_features_reducido - col_means) / col_stds

K_CANDIDATOS = [3, 5, 8, 10, 15, 20]
N_REPETICIONES = 5
FRACCION_ENMASCARADA = 0.10
SEMILLA_BASE = 42

celdas_observadas = np.argwhere(X_std.notna().values)

resultados_busqueda = []
for k in K_CANDIDATOS:
    errores_k = []
    for rep in range(N_REPETICIONES):
        rng = np.random.default_rng(SEMILLA_BASE + rep)
        n_mascara = int(len(celdas_observadas) * FRACCION_ENMASCARADA)
        idx_mascara = rng.choice(len(celdas_observadas), size=n_mascara, replace=False)
        filas_mask, cols_mask = celdas_observadas[idx_mascara].T

        X_con_mascara = X_std.values.copy()
        valores_reales = X_con_mascara[filas_mask, cols_mask].copy()
        X_con_mascara[filas_mask, cols_mask] = np.nan

        imputer = KNNImputer(n_neighbors=k)
        X_imputado_prueba = imputer.fit_transform(X_con_mascara)
        valores_imputados = X_imputado_prueba[filas_mask, cols_mask]

        rmse = np.sqrt(mean_squared_error(valores_reales, valores_imputados))
        errores_k.append(rmse)

    resultados_busqueda.append({
        "k": k, "rmse_promedio": np.mean(errores_k), "rmse_sd": np.std(errores_k)
    })
    print(f"k={k}: RMSE promedio={np.mean(errores_k):.4f} (sd={np.std(errores_k):.4f}) sobre {N_REPETICIONES} repeticiones")

df_busqueda_k = pd.DataFrame(resultados_busqueda).sort_values("rmse_promedio")
K_ELEGIDO = int(df_busqueda_k.iloc[0]["k"])
print(f"\nK elegido (menor RMSE): {K_ELEGIDO}")

df_busqueda_k

k=3: RMSE promedio=0.8713 (sd=0.0084) sobre 5 repeticiones
k=5: RMSE promedio=0.8625 (sd=0.0070) sobre 5 repeticiones
k=8: RMSE promedio=0.8660 (sd=0.0065) sobre 5 repeticiones
k=10: RMSE promedio=0.8694 (sd=0.0061) sobre 5 repeticiones
k=15: RMSE promedio=0.8788 (sd=0.0062) sobre 5 repeticiones
k=20: RMSE promedio=0.8862 (sd=0.0065) sobre 5 repeticiones

K elegido (menor RMSE): 5

    k  rmse_promedio   rmse_sd
1   5       0.862475  0.007042
2   8       0.866048  0.006515
3  10       0.869408  0.006116
0   3       0.871324  0.008366
4  15       0.878813  0.006234
5  20       0.886231  0.006469

In [17]:
imputer_final = KNNImputer(n_neighbors=K_ELEGIDO)
X_imputado_array = imputer_final.fit_transform(X_std)
df_imputado = pd.DataFrame(X_imputado_array, index=X_std.index, columns=X_std.columns)

print(f"Shape df_imputado: {df_imputado.shape}")
print(f"NaN remanentes: {df_imputado.isna().sum().sum()}")

Shape df_imputado: (184, 2058)
NaN remanentes: 0

## 6. Mapeo de variables a dimensión analítica
Se reutiliza la clasificación por dimensión ya calculada en el cuaderno 14 si está en memoria; si no, se reconstruye desde `LLM_dataset_final.xlsx` (columna `groq_dimension_principal_original`) como respaldo — **verificar que coincide con el criterio del cuaderno 14 antes de dar este resultado por definitivo.**

In [18]:
if "df_disponibilidad_variables" in dir():
    mapa_dimension = df_disponibilidad_variables.set_index("codigo")["dimension_principal"].to_dict()
    print("Mapeo de dimension_principal tomado de df_disponibilidad_variables (en memoria).")
else:
    df_disponibilidad_variables = pd.read_excel(IN_PATH, sheet_name="disponibilidad_variables")
    mapa_dimension = df_disponibilidad_variables.set_index("codigo")["dimension_principal"].to_dict()
    print("Mapeo de dimension_principal cargado desde la hoja 'disponibilidad_variables' del Excel del cuaderno 14.")

dimension_por_columna = {
    col: mapa_dimension.get(col.rsplit("_", 1)[0], "SIN_CLASIFICAR")
    for col in df_imputado.columns
}
pd.Series(dimension_por_columna).value_counts()

Mapeo de dimension_principal cargado desde la hoja 'disponibilidad_variables' del Excel del cuaderno 14.

SOCIODEMOGRAFICA    774
ESTRUCTURAL         621
MONETARIA           423
INSTITUCIONAL       240
Name: count, dtype: int64

## 7. PCA por dimensión × estadístico (media, tendencia, volatilidad)
Se corre un PCA independiente para cada combinación de dimensión (MONETARIA, INSTITUCIONAL, ESTRUCTURAL, SOCIODEMOGRAFICA) y estadístico de trayectoria (media, tendencia, volatilidad) — 12 PCA en total, en vez de uno solo por dimensión que mezclaba los tres estadísticos. Esto evita la colinealidad entre media/tendencia/volatilidad de una misma variable. Se protegen de la poda automática las variables consideradas teóricamente centrales por dimensión (tasas de interés y dinero amplio en MONETARIA; calidad institucional y Estado de derecho en INSTITUCIONAL; apertura comercial e inversión en ESTRUCTURAL; población y desigualdad en SOCIODEMOGRAFICA), incluso a costa de un KMO algo menor. Se retienen componentes hasta explicar ≥70% de la varianza.

In [19]:
def es_nivel_absoluto(codigo_base):
    """Indicadores cuyo sufijo de unidad WDI es un nivel monetario absoluto
    (USD o moneda local, corriente o constante) — escalan con el tamaño de
    la economia, no con la politica monetaria-fiscal en si."""
    tokens = codigo_base.split(".")
    return any(t in {"CD", "KD", "CN", "KN"} for t in tokens)

In [20]:
from sklearn.decomposition import PCA
from factor_analyzer.factor_analyzer import calculate_kmo, calculate_bartlett_sphericity

def ejecutar_pca_bloque(df_datos, cols_bloque, nombre_bloque, varianza_objetivo=0.70):
    X = df_datos[cols_bloque]
    kmo_por_item, kmo_global = calculate_kmo(X)
    chi2, p_valor = calculate_bartlett_sphericity(X)
    pca = PCA()
    scores = pca.fit_transform(X)
    var_exp = pca.explained_variance_ratio_
    var_acum = np.cumsum(var_exp)
    n_comp = max(int(np.searchsorted(var_acum, varianza_objetivo) + 1), 1)
    df_scores = pd.DataFrame(scores[:, :n_comp], index=X.index,
                              columns=[f"{nombre_bloque}_PC{i+1}" for i in range(n_comp)])
    df_cargas = pd.DataFrame(pca.components_[:n_comp].T, index=cols_bloque,
                              columns=[f"{nombre_bloque}_PC{i+1}" for i in range(n_comp)])
    print(f"--- {nombre_bloque} ---")
    print(f"N variables: {len(cols_bloque)} | KMO global: {kmo_global:.3f} "
          f"({'adecuado' if kmo_global >= 0.6 else 'BAJO, revisar'}) | Bartlett p-valor: {p_valor:.4g}")
    print(f"Componentes retenidos (>=70% var.): {n_comp} | Var. acumulada: {var_acum[n_comp-1]*100:.1f}%\n")
    return df_scores, df_cargas, var_exp, kmo_global, p_valor


def eliminar_redundantes(df_datos, columnas, umbral=0.95):
    if len(columnas) < 2:
        return columnas
    corr = df_datos[columnas].corr().abs()
    upper = corr.where(np.triu(np.ones(corr.shape, dtype=bool), k=1))
    a_eliminar = set()
    for col in upper.columns:
        if col in a_eliminar:
            continue
        correlacionadas = upper.index[upper[col] > umbral].tolist()
        a_eliminar.update(correlacionadas)
    return [c for c in columnas if c not in a_eliminar]


def podar_hasta_p_menor_n(df_datos, columnas, n_max, umbral_inicial=0.95, paso=0.05, piso=0.20):
    umbral = umbral_inicial
    cols_actuales = columnas
    while len(cols_actuales) >= n_max and umbral > piso:
        cols_actuales = eliminar_redundantes(df_datos, columnas, umbral)
        if len(cols_actuales) >= n_max:
            umbral = round(umbral - paso, 2)
    return cols_actuales, umbral


def seleccionar_por_msa_protegido(df_datos, cols_podables, cols_protegidas,
                                   kmo_objetivo=0.60, min_variables=10, max_iter=500):
    """Poda por MSA calculando siempre el KMO sobre protegidas + podables juntas,
    sacando solo variables NO protegidas. Las protegidas nunca se eliminan."""
    cols_podables = list(cols_podables)
    kmo_global = np.nan
    for _ in range(max_iter):
        cols_actuales = cols_protegidas + cols_podables
        if len(cols_actuales) < 2:
            break
        X = df_datos[cols_actuales]
        kmo_por_item, kmo_global = calculate_kmo(X)
        if not np.isnan(kmo_global) and kmo_global >= kmo_objetivo:
            break
        if len(cols_podables) <= min_variables:
            break
        kmo_series = pd.Series(kmo_por_item, index=cols_actuales)
        kmo_podables = kmo_series[cols_podables]
        if kmo_podables.isna().all():
            cols_podables.pop(0)
        else:
            peor = kmo_podables.idxmin()
            cols_podables.remove(peor)
    return cols_protegidas + cols_podables, kmo_global


CODIGOS_PRECIOS_EXCLUIR_ADICIONAL = ["PA.NUS.PRVT.PLI"]

VARIABLES_PROTEGIDAS = {
    "MONETARIA": ["FR.INR.DPST", "FR.INR.LEND", "FR.INR.RINR",
                  "FM.LBL.BMNY.GD.ZS", "FM.LBL.BMNY.ZG", "FM.LBL.BMNY.CN", "FM.LBL.BMNY.IR.ZS",
                  "FM.AST.CGOV.ZG.M3", "FM.AST.PRVT.ZG.M3", "PA.NUS.FCRF"],
    "INSTITUCIONAL": ["v2x_polyarchy", "GOV_WGI_RQ_SC", "GOV_WGI_RL_SC", "GOV_WGI_CC_SC"],
    "ESTRUCTURAL": ["NE.TRD.GNFS.ZS", "NE.EXP.GNFS.ZS", "NE.IMP.GNFS.ZS", "BX.KLT.DINV.WD.GD.ZS"],
    "SOCIODEMOGRAFICA": ["SP.POP.GROW", "SP.DYN.LE00.IN", "SL.UEM.TOTL.ZS"],
}

ESTADISTICOS = ["media", "tendencia", "volatilidad"]
DIMENSIONES = ["MONETARIA", "INSTITUCIONAL", "ESTRUCTURAL", "SOCIODEMOGRAFICA"]
n_paises = df_imputado.shape[0]

resultados_pca = {}
resumen_poda = []

for dim in DIMENSIONES:
    protegidos_dim = VARIABLES_PROTEGIDAS.get(dim, [])
    for stat in ESTADISTICOS:
        nombre_bloque = f"{dim}_{stat}"
        cols_bloque = [
            c for c, d in dimension_por_columna.items()
            if d == dim and c.endswith(f"_{stat}") and c.rsplit("_", 2)[0] not in CODIGOS_PRECIOS_EXCLUIR_ADICIONAL
        ]
        cols_protegidas = [c for c in cols_bloque if c.rsplit(f"_{stat}", 1)[0] in protegidos_dim]
        cols_podables = [c for c in cols_bloque if c.rsplit(f"_{stat}", 1)[0] not in protegidos_dim]

        if dim == "MONETARIA":
            cols_podables_previo = cols_podables
            cols_podables = [c for c in cols_podables if not es_nivel_absoluto(c.rsplit(f"_{stat}", 1)[0])]
            excluidos_nivel = sorted(set(cols_podables_previo) - set(cols_podables))
            if excluidos_nivel:
                print(f"  [{nombre_bloque}] excluidas por nivel absoluto: {len(excluidos_nivel)} -> {excluidos_nivel}")

        if len(cols_podables) >= n_paises:
            n_objetivo = max(n_paises - len(cols_protegidas) - 10, 30)
            cols_podables, umbral_usado = podar_hasta_p_menor_n(df_imputado, cols_podables, n_objetivo)
        else:
            umbral_usado = "sin poda por correlacion (p<n)"

        cols_final, kmo_final = seleccionar_por_msa_protegido(
            df_imputado, cols_podables, cols_protegidas, kmo_objetivo=0.60, min_variables=15
        )

        print(f"{nombre_bloque}: {len(cols_bloque)} -> {len(cols_final)} variables "
              f"(corr {umbral_usado}, KMO final={kmo_final:.3f}, protegidas={len(cols_protegidas)})")
        resumen_poda.append({"bloque": nombre_bloque, "n_original": len(cols_bloque),
                              "n_final": len(cols_final), "kmo_final": round(kmo_final, 3)})

        resultados_pca[nombre_bloque] = ejecutar_pca_bloque(df_imputado, cols_final, nombre_bloque)

df_pca_scores = pd.concat([resultados_pca[b][0] for b in resultados_pca], axis=1)
print(f"\nShape matriz de scores PCA (12 bloques): {df_pca_scores.shape}")
pd.DataFrame(resumen_poda)

  [MONETARIA_media] excluidas por nivel absoluto: 77 -> ['BM.GSR.TOTL.CD_media', 'BM.KLT.DINV.CD.WD_media', 'BM.TRF.PWKR.CD.DT_media', 'BN.KAC.EOMS.CD_media', 'BN.KLT.DINV.CD_media', 'BN.KLT.PTXL.CD_media', 'BN.RES.INCL.CD_media', 'BX.KLT.DINV.CD.WD_media', 'BX.PEF.TOTL.CD.WD_media', 'FI.RES.TOTL.CD_media', 'FI.RES.XGLD.CD_media', 'FM.AST.DOMS.CN_media', 'FM.AST.NFRG.CN_media', 'GC.REV.GOTR.CN_media', 'GC.REV.XGRT.CN_media', 'GC.TAX.GSRV.CN_media', 'GC.TAX.IMPT.CN_media', 'GC.TAX.INTT.CN_media', 'GC.TAX.OTHR.CN_media', 'GC.TAX.TOTL.CN_media', 'GC.TAX.YPKG.CN_media', 'GC.XPN.COMP.CN_media', 'GC.XPN.GSRV.CN_media', 'GC.XPN.INTP.CN_media', 'GC.XPN.OTHR.CN_media', 'GC.XPN.TOTL.CN_media', 'GC.XPN.TRFT.CN_media', 'NE.CON.GOVT.CD_media', 'NE.CON.GOVT.CN_media', 'NE.CON.GOVT.KD.ZG_media', 'NE.CON.GOVT.KD_media', 'NE.CON.GOVT.KN_media', 'NE.CON.TOTL.CD_media', 'NE.CON.TOTL.CN_media', 'NE.CON.TOTL.KD.ZG_media', 'NE.CON.TOTL.KD_media', 'NE.CON.TOTL.KN_media', 'NE.DAB.TOTL.CD_media', 'NE.DAB.TOTL.CN_media', 'NE.DAB.TOTL.KD_media', 'NE.DAB.TOTL.KN_media', 'NE.IMP.GNFS.CN_media', 'NY.ADJ.AEDU.CD_media', 'NY.ADJ.DCO2.CD_media', 'NY.ADJ.DFOR.CD_media', 'NY.ADJ.NNAT.CD_media', 'NY.ADJ.NNTY.CD_media', 'NY.ADJ.NNTY.KD.ZG_media', 'NY.ADJ.NNTY.KD_media', 'NY.ADJ.SVNG.CD_media', 'NY.ADJ.SVNX.CD_media', 'NY.GDP.MKTP.CD_media', 'NY.GDP.MKTP.KD.ZG_media', 'NY.GDP.MKTP.KD_media', 'NY.GDP.MKTP.PP.CD_media', 'NY.GDP.MKTP.PP.KD_media', 'NY.GDS.TOTL.CD_media', 'NY.GDS.TOTL.CN_media', 'NY.GDY.TOTL.KN_media', 'NY.GNP.ATLS.CD_media', 'NY.GNP.MKTP.CD_media', 'NY.GNP.MKTP.CN.AD_media', 'NY.GNP.MKTP.CN_media', 'NY.GNP.MKTP.KD.ZG_media', 'NY.GNP.MKTP.KD_media', 'NY.GNP.MKTP.KN_media', 'NY.GNP.MKTP.PP.CD_media', 'NY.GNS.ICTR.CD_media', 'NY.GNS.ICTR.CN_media', 'SH.XPD.CHEX.PC.CD_media', 'SH.XPD.CHEX.PP.CD_media', 'SH.XPD.EHEX.PC.CD_media', 'SH.XPD.EHEX.PP.CD_media', 'SH.XPD.GHED.PC.CD_media', 'SH.XPD.GHED.PP.CD_media', 'SH.XPD.OOPC.PC.CD_media', 'TM.VAL.SERV.CD.WT_media']
MONETARIA_media: 140 -> 63 variables (corr sin poda por correlacion (p<n), KMO final=0.701, protegidas=10)
--- MONETARIA_media ---
N variables: 63 | KMO global: 0.701 (adecuado) | Bartlett p-valor: 0
Componentes retenidos (>=70% var.): 11 | Var. acumulada: 71.7%

  [MONETARIA_tendencia] excluidas por nivel absoluto: 77 -> ['BM.GSR.TOTL.CD_tendencia', 'BM.KLT.DINV.CD.WD_tendencia', 'BM.TRF.PWKR.CD.DT_tendencia', 'BN.KAC.EOMS.CD_tendencia', 'BN.KLT.DINV.CD_tendencia', 'BN.KLT.PTXL.CD_tendencia', 'BN.RES.INCL.CD_tendencia', 'BX.KLT.DINV.CD.WD_tendencia', 'BX.PEF.TOTL.CD.WD_tendencia', 'FI.RES.TOTL.CD_tendencia', 'FI.RES.XGLD.CD_tendencia', 'FM.AST.DOMS.CN_tendencia', 'FM.AST.NFRG.CN_tendencia', 'GC.REV.GOTR.CN_tendencia', 'GC.REV.XGRT.CN_tendencia', 'GC.TAX.GSRV.CN_tendencia', 'GC.TAX.IMPT.CN_tendencia', 'GC.TAX.INTT.CN_tendencia', 'GC.TAX.OTHR.CN_tendencia', 'GC.TAX.TOTL.CN_tendencia', 'GC.TAX.YPKG.CN_tendencia', 'GC.XPN.COMP.CN_tendencia', 'GC.XPN.GSRV.CN_tendencia', 'GC.XPN.INTP.CN_tendencia', 'GC.XPN.OTHR.CN_tendencia', 'GC.XPN.TOTL.CN_tendencia', 'GC.XPN.TRFT.CN_tendencia', 'NE.CON.GOVT.CD_tendencia', 'NE.CON.GOVT.CN_tendencia', 'NE.CON.GOVT.KD.ZG_tendencia', 'NE.CON.GOVT.KD_tendencia', 'NE.CON.GOVT.KN_tendencia', 'NE.CON.TOTL.CD_tendencia', 'NE.CON.TOTL.CN_tendencia', 'NE.CON.TOTL.KD.ZG_tendencia', 'NE.CON.TOTL.KD_tendencia', 'NE.CON.TOTL.KN_tendencia', 'NE.DAB.TOTL.CD_tendencia', 'NE.DAB.TOTL.CN_tendencia', 'NE.DAB.TOTL.KD_tendencia', 'NE.DAB.TOTL.KN_tendencia', 'NE.IMP.GNFS.CN_tendencia', 'NY.ADJ.AEDU.CD_tendencia', 'NY.ADJ.DCO2.CD_tendencia', 'NY.ADJ.DFOR.CD_tendencia', 'NY.ADJ.NNAT.CD_tendencia', 'NY.ADJ.NNTY.CD_tendencia', 'NY.ADJ.NNTY.KD.ZG_tendencia', 'NY.ADJ.NNTY.KD_tendencia', 'NY.ADJ.SVNG.CD_tendencia', 'NY.ADJ.SVNX.CD_tendencia', 'NY.GDP.MKTP.CD_tendencia', 'NY.GDP.MKTP.KD.ZG_tendencia', 'NY.GDP.MKTP.KD_tendencia', 'NY.GDP.MKTP.PP.CD_tendencia', 'NY.GDP.MKTP.PP.KD_tendencia', 'NY.GDS.TOTL.CD_tendencia', 'NY.GDS.TOTL.CN_tendencia', 'NY.GDY.TOTL.KN_tendencia', 'NY.GNP.ATLS.CD_tendencia', 'NY.GNP.MKTP.CD_tendencia', 'NY.GNP.MKTP.CN.AD_tendencia', 'NY.GNP.MKTP.CN_tendencia', 'NY.GNP.MKTP.KD.ZG_tendencia', 'NY.GNP.MKTP.KD_tendencia', 'NY.GNP.MKTP.KN_tendencia', 'NY.GNP.MKTP.PP.CD_tendencia', 'NY.GNS.ICTR.CD_tendencia', 'NY.GNS.ICTR.CN_tendencia', 'SH.XPD.CHEX.PC.CD_tendencia', 'SH.XPD.CHEX.PP.CD_tendencia', 'SH.XPD.EHEX.PC.CD_tendencia', 'SH.XPD.EHEX.PP.CD_tendencia', 'SH.XPD.GHED.PC.CD_tendencia', 'SH.XPD.GHED.PP.CD_tendencia', 'SH.XPD.OOPC.PC.CD_tendencia', 'TM.VAL.SERV.CD.WT_tendencia']
MONETARIA_tendencia: 140 -> 60 variables (corr sin poda por correlacion (p<n), KMO final=0.601, protegidas=10)
--- MONETARIA_tendencia ---
N variables: 60 | KMO global: 0.601 (adecuado) | Bartlett p-valor: 0
Componentes retenidos (>=70% var.): 13 | Var. acumulada: 71.4%

  [MONETARIA_volatilidad] excluidas por nivel absoluto: 77 -> ['BM.GSR.TOTL.CD_volatilidad', 'BM.KLT.DINV.CD.WD_volatilidad', 'BM.TRF.PWKR.CD.DT_volatilidad', 'BN.KAC.EOMS.CD_volatilidad', 'BN.KLT.DINV.CD_volatilidad', 'BN.KLT.PTXL.CD_volatilidad', 'BN.RES.INCL.CD_volatilidad', 'BX.KLT.DINV.CD.WD_volatilidad', 'BX.PEF.TOTL.CD.WD_volatilidad', 'FI.RES.TOTL.CD_volatilidad', 'FI.RES.XGLD.CD_volatilidad', 'FM.AST.DOMS.CN_volatilidad', 'FM.AST.NFRG.CN_volatilidad', 'GC.REV.GOTR.CN_volatilidad', 'GC.REV.XGRT.CN_volatilidad', 'GC.TAX.GSRV.CN_volatilidad', 'GC.TAX.IMPT.CN_volatilidad', 'GC.TAX.INTT.CN_volatilidad', 'GC.TAX.OTHR.CN_volatilidad', 'GC.TAX.TOTL.CN_volatilidad', 'GC.TAX.YPKG.CN_volatilidad', 'GC.XPN.COMP.CN_volatilidad', 'GC.XPN.GSRV.CN_volatilidad', 'GC.XPN.INTP.CN_volatilidad', 'GC.XPN.OTHR.CN_volatilidad', 'GC.XPN.TOTL.CN_volatilidad', 'GC.XPN.TRFT.CN_volatilidad', 'NE.CON.GOVT.CD_volatilidad', 'NE.CON.GOVT.CN_volatilidad', 'NE.CON.GOVT.KD.ZG_volatilidad', 'NE.CON.GOVT.KD_volatilidad', 'NE.CON.GOVT.KN_volatilidad', 'NE.CON.TOTL.CD_volatilidad', 'NE.CON.TOTL.CN_volatilidad', 'NE.CON.TOTL.KD.ZG_volatilidad', 'NE.CON.TOTL.KD_volatilidad', 'NE.CON.TOTL.KN_volatilidad', 'NE.DAB.TOTL.CD_volatilidad', 'NE.DAB.TOTL.CN_volatilidad', 'NE.DAB.TOTL.KD_volatilidad', 'NE.DAB.TOTL.KN_volatilidad', 'NE.IMP.GNFS.CN_volatilidad', 'NY.ADJ.AEDU.CD_volatilidad', 'NY.ADJ.DCO2.CD_volatilidad', 'NY.ADJ.DFOR.CD_volatilidad', 'NY.ADJ.NNAT.CD_volatilidad', 'NY.ADJ.NNTY.CD_volatilidad', 'NY.ADJ.NNTY.KD.ZG_volatilidad', 'NY.ADJ.NNTY.KD_volatilidad', 'NY.ADJ.SVNG.CD_volatilidad', 'NY.ADJ.SVNX.CD_volatilidad', 'NY.GDP.MKTP.CD_volatilidad', 'NY.GDP.MKTP.KD.ZG_volatilidad', 'NY.GDP.MKTP.KD_volatilidad', 'NY.GDP.MKTP.PP.CD_volatilidad', 'NY.GDP.MKTP.PP.KD_volatilidad', 'NY.GDS.TOTL.CD_volatilidad', 'NY.GDS.TOTL.CN_volatilidad', 'NY.GDY.TOTL.KN_volatilidad', 'NY.GNP.ATLS.CD_volatilidad', 'NY.GNP.MKTP.CD_volatilidad', 'NY.GNP.MKTP.CN.AD_volatilidad', 'NY.GNP.MKTP.CN_volatilidad', 'NY.GNP.MKTP.KD.ZG_volatilidad', 'NY.GNP.MKTP.KD_volatilidad', 'NY.GNP.MKTP.KN_volatilidad', 'NY.GNP.MKTP.PP.CD_volatilidad', 'NY.GNS.ICTR.CD_volatilidad', 'NY.GNS.ICTR.CN_volatilidad', 'SH.XPD.CHEX.PC.CD_volatilidad', 'SH.XPD.CHEX.PP.CD_volatilidad', 'SH.XPD.EHEX.PC.CD_volatilidad', 'SH.XPD.EHEX.PP.CD_volatilidad', 'SH.XPD.GHED.PC.CD_volatilidad', 'SH.XPD.GHED.PP.CD_volatilidad', 'SH.XPD.OOPC.PC.CD_volatilidad', 'TM.VAL.SERV.CD.WT_volatilidad']
MONETARIA_volatilidad: 140 -> 63 variables (corr sin poda por correlacion (p<n), KMO final=0.719, protegidas=10)
--- MONETARIA_volatilidad ---
N variables: 63 | KMO global: 0.719 (adecuado) | Bartlett p-valor: 0
Componentes retenidos (>=70% var.): 12 | Var. acumulada: 70.8%

INSTITUCIONAL_media: 80 -> 80 variables (corr sin poda por correlacion (p<n), KMO final=0.915, protegidas=3)
--- INSTITUCIONAL_media ---
N variables: 80 | KMO global: 0.915 (adecuado) | Bartlett p-valor: nan
Componentes retenidos (>=70% var.): 5 | Var. acumulada: 70.3%

INSTITUCIONAL_tendencia: 80 -> 80 variables (corr sin poda por correlacion (p<n), KMO final=0.805, protegidas=3)

c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\factor_analyzer.py:109: RuntimeWarning: invalid value encountered in log
  statistic = -np.log(corr_det) * (n - 1 - (2 * p + 5) / 6)
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\factor_analyzer.py:109: RuntimeWarning: invalid value encountered in log
  statistic = -np.log(corr_det) * (n - 1 - (2 * p + 5) / 6)
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(

--- INSTITUCIONAL_tendencia ---
N variables: 80 | KMO global: 0.805 (adecuado) | Bartlett p-valor: nan
Componentes retenidos (>=70% var.): 13 | Var. acumulada: 71.2%

INSTITUCIONAL_volatilidad: 80 -> 80 variables (corr sin poda por correlacion (p<n), KMO final=0.847, protegidas=3)
--- INSTITUCIONAL_volatilidad ---
N variables: 80 | KMO global: 0.847 (adecuado) | Bartlett p-valor: 0
Componentes retenidos (>=70% var.): 14 | Var. acumulada: 71.5%

c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:199: RuntimeWarning: invalid value encountered in sqrt
  Is = np.sqrt(1 / np.diag(m))
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:199: RuntimeWarning: invalid value encountered in sqrt
  Is = np.sqrt(1 / np.diag(m))
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:199: RuntimeWarning: invalid value encountered in sqrt
  Is = np.sqrt(1 / np.diag(m))
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:199: RuntimeWarning: invalid value encountered in sqrt
  Is = np.sqrt(1 / np.diag(m))
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:199: RuntimeWarning: invalid value encountered in sqrt
  Is = np.sqrt(1 / np.diag(m))
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:199: RuntimeWarning: invalid value encountered in sqrt
  Is = np.sqrt(1 / np.diag(m))
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:199: RuntimeWarning: invalid value encountered in sqrt
  Is = np.sqrt(1 / np.diag(m))
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:199: RuntimeWarning: invalid value encountered in sqrt
  Is = np.sqrt(1 / np.diag(m))
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:199: RuntimeWarning: invalid value encountered in sqrt
  Is = np.sqrt(1 / np.diag(m))
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:199: RuntimeWarning: invalid value encountered in sqrt
  Is = np.sqrt(1 / np.diag(m))
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:199: RuntimeWarning: invalid value encountered in sqrt
  Is = np.sqrt(1 / np.diag(m))
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:199: RuntimeWarning: invalid value encountered in sqrt
  Is = np.sqrt(1 / np.diag(m))
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:199: RuntimeWarning: invalid value encountered in sqrt
  Is = np.sqrt(1 / np.diag(m))
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:199: RuntimeWarning: invalid value encountered in sqrt
  Is = np.sqrt(1 / np.diag(m))
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:199: RuntimeWarning: invalid value encountered in sqrt
  Is = np.sqrt(1 / np.diag(m))
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:199: RuntimeWarning: invalid value encountered in sqrt
  Is = np.sqrt(1 / np.diag(m))
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:199: RuntimeWarning: invalid value encountered in sqrt
  Is = np.sqrt(1 / np.diag(m))
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:199: RuntimeWarning: invalid value encountered in sqrt
  Is = np.sqrt(1 / np.diag(m))
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:199: RuntimeWarning: invalid value encountered in sqrt
  Is = np.sqrt(1 / np.diag(m))
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:199: RuntimeWarning: invalid value encountered in sqrt
  Is = np.sqrt(1 / np.diag(m))
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:199: RuntimeWarning: invalid value encountered in sqrt
  Is = np.sqrt(1 / np.diag(m))
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:199: RuntimeWarning: invalid value encountered in sqrt
  Is = np.sqrt(1 / np.diag(m))
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:199: RuntimeWarning: invalid value encountered in sqrt
  Is = np.sqrt(1 / np.diag(m))
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:199: RuntimeWarning: invalid value encountered in sqrt
  Is = np.sqrt(1 / np.diag(m))
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\factor_analyzer.py:109: RuntimeWarning: invalid value encountered in log
  statistic = -np.log(corr_det) * (n - 1 - (2 * p + 5) / 6)

ESTRUCTURAL_media: 207 -> 120 variables (corr 0.95, KMO final=0.614, protegidas=4)
--- ESTRUCTURAL_media ---
N variables: 120 | KMO global: 0.614 (adecuado) | Bartlett p-valor: nan
Componentes retenidos (>=70% var.): 16 | Var. acumulada: 70.8%

c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:199: RuntimeWarning: invalid value encountered in sqrt
  Is = np.sqrt(1 / np.diag(m))
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:199: RuntimeWarning: invalid value encountered in sqrt
  Is = np.sqrt(1 / np.diag(m))
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:199: RuntimeWarning: invalid value encountered in sqrt
  Is = np.sqrt(1 / np.diag(m))
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:199: RuntimeWarning: invalid value encountered in sqrt
  Is = np.sqrt(1 / np.diag(m))
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:199: RuntimeWarning: invalid value encountered in sqrt
  Is = np.sqrt(1 / np.diag(m))
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:199: RuntimeWarning: invalid value encountered in sqrt
  Is = np.sqrt(1 / np.diag(m))
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:199: RuntimeWarning: invalid value encountered in sqrt
  Is = np.sqrt(1 / np.diag(m))
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:199: RuntimeWarning: invalid value encountered in sqrt
  Is = np.sqrt(1 / np.diag(m))
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:199: RuntimeWarning: invalid value encountered in sqrt
  Is = np.sqrt(1 / np.diag(m))
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\factor_analyzer.py:109: RuntimeWarning: invalid value encountered in log
  statistic = -np.log(corr_det) * (n - 1 - (2 * p + 5) / 6)

ESTRUCTURAL_tendencia: 207 -> 118 variables (corr 0.95, KMO final=0.603, protegidas=4)
--- ESTRUCTURAL_tendencia ---
N variables: 118 | KMO global: 0.603 (adecuado) | Bartlett p-valor: nan
Componentes retenidos (>=70% var.): 19 | Var. acumulada: 70.2%

c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(

ESTRUCTURAL_volatilidad: 207 -> 156 variables (corr 0.95, KMO final=0.611, protegidas=4)
--- ESTRUCTURAL_volatilidad ---
N variables: 156 | KMO global: 0.611 (adecuado) | Bartlett p-valor: 0
Componentes retenidos (>=70% var.): 19 | Var. acumulada: 70.4%

SOCIODEMOGRAFICA_media: 258 -> 124 variables (corr 0.95, KMO final=0.796, protegidas=3)
--- SOCIODEMOGRAFICA_media ---
N variables: 124 | KMO global: 0.796 (adecuado) | Bartlett p-valor: 0
Componentes retenidos (>=70% var.): 10 | Var. acumulada: 71.0%

c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(

SOCIODEMOGRAFICA_tendencia: 258 -> 139 variables (corr 0.9, KMO final=0.605, protegidas=3)
--- SOCIODEMOGRAFICA_tendencia ---
N variables: 139 | KMO global: 0.605 (adecuado) | Bartlett p-valor: 0
Componentes retenidos (>=70% var.): 21 | Var. acumulada: 70.2%

c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(

SOCIODEMOGRAFICA_volatilidad: 258 -> 142 variables (corr 0.9, KMO final=0.604, protegidas=3)
--- SOCIODEMOGRAFICA_volatilidad ---
N variables: 142 | KMO global: 0.604 (adecuado) | Bartlett p-valor: 0
Componentes retenidos (>=70% var.): 20 | Var. acumulada: 70.7%


Shape matriz de scores PCA (12 bloques): (184, 173)

c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(
c:\Users\Carmela\AppData\Local\Programs\Python\Python312\Lib\site-packages\factor_analyzer\utils.py:244: UserWarning: The inverse of the variance-covariance matrix was calculated using the Moore-Penrose generalized matrix inversion, due to its determinant being at or very close to zero.
  warnings.warn(

                          bloque  n_original  n_final  kmo_final
0                MONETARIA_media         140       63      0.701
1            MONETARIA_tendencia         140       60      0.601
2          MONETARIA_volatilidad         140       63      0.719
3            INSTITUCIONAL_media          80       80      0.915
4        INSTITUCIONAL_tendencia          80       80      0.805
5      INSTITUCIONAL_volatilidad          80       80      0.847
6              ESTRUCTURAL_media         207      120      0.614
7          ESTRUCTURAL_tendencia         207      118      0.603
8        ESTRUCTURAL_volatilidad         207      156      0.611
9         SOCIODEMOGRAFICA_media         258      124      0.796
10    SOCIODEMOGRAFICA_tendencia         258      139      0.605
11  SOCIODEMOGRAFICA_volatilidad         258      142      0.604

## 8. Interpretación de cargas factoriales (PC1 y PC2 por bloque)
Variables con mayor peso absoluto en los dos primeros componentes de cada uno de los 12 bloques (dimensión × estadístico) — necesario para nombrar/interpretar conceptualmente cada componente. Ningún componente se acepta sin sentido teórico.

In [21]:
for nombre_bloque, (scores, cargas, var_exp, kmo, p) in resultados_pca.items():
    print(f"=== {nombre_bloque} — Top cargas PC1 ===")
    print(cargas.iloc[:, 0].abs().sort_values(ascending=False).head(8))
    if cargas.shape[1] > 1:
        print(f"\n=== {nombre_bloque} — Top cargas PC2 ===")
        print(cargas.iloc[:, 1].abs().sort_values(ascending=False).head(8))
    print("\n" + "="*60 + "\n")

=== MONETARIA_media — Top cargas PC1 ===
SH.XPD.GHED.GD.ZS_media    0.272050
FD.AST.PRVT.GD.ZS_media    0.253640
FM.AST.PRVT.GD.ZS_media    0.253343
FS.AST.PRVT.GD.ZS_media    0.252742
SH.XPD.GHED.CH.ZS_media    0.240002
PA.NUS.GDP.PLI_media       0.236724
SH.XPD.GHED.GE.ZS_media    0.213071
GC.XPN.TOTL.GD.ZS_media    0.203883
Name: MONETARIA_media_PC1, dtype: float64

=== MONETARIA_media — Top cargas PC2 ===
NY.ADJ.ICTR.GN.ZS_media    0.350331
NY.GNS.ICTR.GN.ZS_media    0.344902
NY.GDS.TOTL.ZS_media       0.323475
NE.CON.TOTL.ZS_media       0.323475
NY.ADJ.NNAT.GN.ZS_media    0.316282
NE.DAB.TOTL.ZS_media       0.270411
NY.GNS.ICTR.ZS_media       0.253107
SH.XPD.CHEX.GD.ZS_media    0.201565
Name: MONETARIA_media_PC2, dtype: float64

============================================================

=== MONETARIA_tendencia — Top cargas PC1 ===
NY.GNS.ICTR.ZS_tendencia       0.338512
GC.REV.XGRT.GD.ZS_tendencia    0.302465
GC.TAX.TOTL.GD.ZS_tendencia    0.294293
GC.NLD.TOTL.GD.ZS_tendencia    0.292821
NY.ADJ.NNAT.GN.ZS_tendencia    0.283426
NY.ADJ.ICTR.GN.ZS_tendencia    0.282416
NY.GNS.ICTR.GN.ZS_tendencia    0.231687
NY.ADJ.SVNG.GN.ZS_tendencia    0.225099
Name: MONETARIA_tendencia_PC1, dtype: float64

=== MONETARIA_tendencia — Top cargas PC2 ===
NE.CON.TOTL.ZS_tendencia       0.261207
NY.GDS.TOTL.ZS_tendencia       0.261207
NE.DAB.TOTL.ZS_tendencia       0.253657
SH.XPD.GHED.GE.ZS_tendencia    0.234041
NE.CON.GOVT.ZS_tendencia       0.230456
SH.XPD.GHED.GD.ZS_tendencia    0.228666
FM.AST.PRVT.GD.ZS_tendencia    0.227063
FD.AST.PRVT.GD.ZS_tendencia    0.225016
Name: MONETARIA_tendencia_PC2, dtype: float64

============================================================

=== MONETARIA_volatilidad — Top cargas PC1 ===
NY.ADJ.ICTR.GN.ZS_volatilidad    0.246426
NY.ADJ.NNAT.GN.ZS_volatilidad    0.239977
NY.GDS.TOTL.ZS_volatilidad       0.238600
NE.CON.TOTL.ZS_volatilidad       0.238600
NY.GNS.ICTR.GN.ZS_volatilidad    0.233997
NY.ADJ.SVNG.GN.ZS_volatilidad    0.227116
NE.DAB.TOTL.ZS_volatilidad       0.222609
NE.CON.GOVT.ZS_volatilidad       0.204308
Name: MONETARIA_volatilidad_PC1, dtype: float64

=== MONETARIA_volatilidad — Top cargas PC2 ===
FD.AST.PRVT.GD.ZS_volatilidad    0.339350
FM.AST.PRVT.GD.ZS_volatilidad    0.339293
FS.AST.PRVT.GD.ZS_volatilidad    0.329247
FM.AST.PRVT.ZG.M3_volatilidad    0.236112
GC.XPN.TOTL.GD.ZS_volatilidad    0.224618
FM.AST.DOMO.ZG.M3_volatilidad    0.213809
PA.NUS.GDP.PLI_volatilidad       0.203653
FB.CBK.BRCH.P5_volatilidad       0.200892
Name: MONETARIA_volatilidad_PC2, dtype: float64

============================================================

=== INSTITUCIONAL_media — Top cargas PC1 ===
GOV_WGI_VA_SC_media              0.157129
GOV_WGI_VA_EST_media             0.157129
v2x_regime_amb_media             0.145854
v2xnp_pres_media                 0.143512
GOV_WGI_RL_SC_media              0.142822
GOV_WGI_RL_EST_media             0.142822
v2x_jucon_media                  0.140907
v2x_electoral_integrity_media    0.140547
Name: INSTITUCIONAL_media_PC1, dtype: float64

=== INSTITUCIONAL_media — Top cargas PC2 ===
v2xel_elecpres_media       0.225512
v2x_suffr_media            0.197432
v2x_ex_direlect_media      0.195445
v2x_ex_hereditary_media    0.192025
v2xme_altinf_media         0.186718
GOV_WGI_CC_SC_media        0.182924
GOV_WGI_CC_EST_media       0.182924
GOV_WGI_GE_EST_media       0.176586
Name: INSTITUCIONAL_media_PC2, dtype: float64

============================================================

=== INSTITUCIONAL_tendencia — Top cargas PC1 ===
v2x_electoral_integrity_tendencia    0.198597
v2x_diagacc_tendencia                0.195311
GOV_WGI_VA_SC_tendencia              0.190076
GOV_WGI_VA_EST_tendencia             0.190076
v2xme_altinf_tendencia               0.188410
v2x_horacc_tendencia                 0.186203
v2xnp_pres_tendencia                 0.184662
v2xcl_disc_tendencia                 0.182959
Name: INSTITUCIONAL_tendencia_PC1, dtype: float64

=== INSTITUCIONAL_tendencia — Top cargas PC2 ===
GOV_WGI_GE_SC_tendencia     0.284879
GOV_WGI_GE_EST_tendencia    0.284879
GOV_WGI_RQ_EST_tendencia    0.262421
GOV_WGI_RQ_SC_tendencia     0.262421
GOV_WGI_RL_EST_tendencia    0.256377
GOV_WGI_RL_SC_tendencia     0.256377
GOV_WGI_CC_EST_tendencia    0.255258
GOV_WGI_CC_SC_tendencia     0.255258
Name: INSTITUCIONAL_tendencia_PC2, dtype: float64

============================================================

=== INSTITUCIONAL_volatilidad — Top cargas PC1 ===
v2x_electoral_integrity_volatilidad    0.183991
v2x_diagacc_volatilidad                0.178333
v2xnp_pres_volatilidad                 0.174243
v2xme_altinf_volatilidad               0.174077
v2xedvd_me_cent_volatilidad            0.173520
v2xcl_disc_volatilidad                 0.173202
v2xcs_ccsi_volatilidad                 0.170522
v2xdl_delib_volatilidad                0.166369
Name: INSTITUCIONAL_volatilidad_PC1, dtype: float64

=== INSTITUCIONAL_volatilidad — Top cargas PC2 ===
v2x_egaldem_stock_volatilidad      0.224599
v2x_elecreg_volatilidad            0.222343
v2x_delibdem_stock_volatilidad     0.217068
v2x_partipdem_stock_volatilidad    0.210443
v2x_libdem_stock_volatilidad       0.208900
v2x_genpp_volatilidad              0.196931
v2xex_elecleg_volatilidad          0.193749
v2x_ex_military_volatilidad        0.192660
Name: INSTITUCIONAL_volatilidad_PC2, dtype: float64

============================================================

=== ESTRUCTURAL_media — Top cargas PC1 ===
SL.EMP.WORK.ZS_media       0.178416
SL.AGR.EMPL.ZS_media       0.173935
FB.ATM.TOTL.P5_media       0.168465
SL.GDP.PCAP.EM.KD_media    0.168107
NV.AGR.TOTL.ZS_media       0.167967
NV.SRV.EMPL.KD_media       0.162885
SL.IND.EMPL.MA.ZS_media    0.162267
SL.SRV.EMPL.ZS_media       0.160424
Name: ESTRUCTURAL_media_PC1, dtype: float64

=== ESTRUCTURAL_media — Top cargas PC2 ===
NY.GDP.TOTL.RT.ZS_media    0.249982
NV.IND.TOTL.ZS_media       0.249514
NY.GDP.PETR.RT.ZS_media    0.246127
TX.VAL.FUEL.ZS.UN_media    0.235095
NY.ADJ.DNGY.GN.ZS_media    0.233877
NY.ADJ.DRES.GN.ZS_media    0.213537
TT.PRI.MRCH.XD.WD_media    0.202351
EG.IMP.CONS.ZS_media       0.200340
Name: ESTRUCTURAL_media_PC2, dtype: float64

============================================================

=== ESTRUCTURAL_tendencia — Top cargas PC1 ===
TX.VAL.MRCH.WL.CD_tendencia    0.247991
NV.SRV.TOTL.CD_tendencia       0.246909
NE.IMP.GNFS.KD_tendencia       0.243748
NY.ADJ.DKAP.CD_tendencia       0.234994
TX.VAL.SERV.CD.WT_tendencia    0.224941
ST.INT.RCPT.CD_tendencia       0.217902
NE.GDI.FTOT.KD_tendencia       0.214809
IS.AIR.PSGR_tendencia          0.211513
Name: ESTRUCTURAL_tendencia_PC1, dtype: float64

=== ESTRUCTURAL_tendencia — Top cargas PC2 ===
NY.GDP.PETR.RT.ZS_tendencia    0.258648
TM.VAL.MRCH.R6.ZS_tendencia    0.252562
NY.ADJ.DRES.GN.ZS_tendencia    0.250633
NY.GDP.TOTL.RT.ZS_tendencia    0.234814
TM.VAL.MRCH.R5.ZS_tendencia    0.229318
TM.VAL.MRCH.WR.ZS_tendencia    0.226128
NV.IND.TOTL.ZS_tendencia       0.209091
TX.VAL.INSF.ZS.WT_tendencia    0.204652
Name: ESTRUCTURAL_tendencia_PC2, dtype: float64

============================================================

=== ESTRUCTURAL_volatilidad — Top cargas PC1 ===
TM.VAL.MRCH.WL.CD_volatilidad    0.154609
BN.GSR.FCTY.CD_volatilidad       0.146365
TX.VAL.SERV.CD.WT_volatilidad    0.143309
NE.IMP.GNFS.KD_volatilidad       0.142762
TX.VAL.MRCH.WL.CD_volatilidad    0.142206
NV.SRV.TOTL.CD_volatilidad       0.140873
BM.GSR.NFSV.CD_volatilidad       0.139210
NV.IND.TOTL.CD_volatilidad       0.139202
Name: ESTRUCTURAL_volatilidad_PC1, dtype: float64

=== ESTRUCTURAL_volatilidad — Top cargas PC2 ===
NY.GDP.TOTL.RT.ZS_volatilidad    0.143192
NY.ADJ.DNGY.CD_volatilidad       0.141534
IP.JRN.ARTC.SC_volatilidad       0.140569
NV.AGR.TOTL.CD_volatilidad       0.138714
NV.IND.TOTL.CD_volatilidad       0.138252
NY.ADJ.DRES.GN.ZS_volatilidad    0.136086
NV.IND.TOTL.ZS_volatilidad       0.135234
NE.GDI.TOTL.CD_volatilidad       0.133443
Name: ESTRUCTURAL_volatilidad_PC2, dtype: float64

============================================================

=== SOCIODEMOGRAFICA_media — Top cargas PC1 ===
SP.POP.DPND.YG_media       0.157009
SP.DYN.LE00.IN_media       0.153914
SE.SEC.ENRR.MA_media       0.152927
SH.STA.BASS.ZS_media       0.152505
SP.DYN.TO65.FE.ZS_media    0.149103
SH.H2O.BASW.ZS_media       0.148179
EG.ELC.ACCS.ZS_media       0.148174
SH.STA.STNT.ME.ZS_media    0.147727
Name: SOCIODEMOGRAFICA_media_PC1, dtype: float64

=== SOCIODEMOGRAFICA_media — Top cargas PC2 ===
SL.TLF.CACT.ZS_media            0.236450
SL.TLF.ACTI.ZS_media            0.234658
SL.TLF.ACTI.1524.ZS_media       0.228284
SL.TLF.ACTI.1524.FE.ZS_media    0.226531
SL.TLF.CACT.NE.ZS_media         0.224778
SL.UEM.TOTL.FE.ZS_media         0.224592
SL.UEM.TOTL.FE.NE.ZS_media      0.219578
SL.EMP.1524.SP.MA.ZS_media      0.216174
Name: SOCIODEMOGRAFICA_media_PC2, dtype: float64

============================================================

=== SOCIODEMOGRAFICA_tendencia — Top cargas PC1 ===
SP.DYN.IMRT.MA.IN_tendencia       0.169814
SP.DYN.CDRT.IN_tendencia          0.156336
SH.STA.MMRT_tendencia             0.153243
SE.SEC.ENRL.FE.ZS_tendencia       0.151104
SE.ENR.PRSC.FM.ZS_tendencia       0.150763
SE.SEC.ENRL.GC.FE.ZS_tendencia    0.150682
SP.DYN.TFRT.IN_tendencia          0.150040
EG.ELC.ACCS.ZS_tendencia          0.148830
Name: SOCIODEMOGRAFICA_tendencia_PC1, dtype: float64

=== SOCIODEMOGRAFICA_tendencia — Top cargas PC2 ===
SL.EMP.TOTL.SP.MA.ZS_tendencia    0.230881
SL.UEM.TOTL.ZS_tendencia          0.215749
SL.UEM.TOTL.MA.ZS_tendencia       0.215183
SL.UEM.1524.ZS_tendencia          0.213707
SP.POP.1519.MA.5Y_tendencia       0.212863
SL.UEM.NEET.MA.ME.ZS_tendencia    0.198257
SP.POP.3034.MA.5Y_tendencia       0.193729
SP.DYN.TO65.MA.ZS_tendencia       0.186362
Name: SOCIODEMOGRAFICA_tendencia_PC2, dtype: float64

============================================================

=== SOCIODEMOGRAFICA_volatilidad — Top cargas PC1 ===
SP.POP.7074.MA.5Y_volatilidad    0.167324
EG.ELC.ACCS.UR.ZS_volatilidad    0.160032
SP.POP.DPND.OL_volatilidad       0.156009
EG.ELC.ACCS.ZS_volatilidad       0.152105
SP.POP.6569.MA.5Y_volatilidad    0.151393
SE.PRM.REPT.ZS_volatilidad       0.150880
SP.POP.7579.MA.5Y_volatilidad    0.150319
SP.POP.5559.MA.5Y_volatilidad    0.147953
Name: SOCIODEMOGRAFICA_volatilidad_PC1, dtype: float64

=== SOCIODEMOGRAFICA_volatilidad — Top cargas PC2 ===
SP.POP.2529.MA.5Y_volatilidad    0.218663
SP.POP.2024.MA.5Y_volatilidad    0.213548
SP.POP.DPND.YG_volatilidad       0.207385
SP.POP.2529.FE.5Y_volatilidad    0.205321
SP.POP.1014.MA.5Y_volatilidad    0.198715
SP.POP.0509.MA.5Y_volatilidad    0.194028
SP.POP.1519.MA.5Y_volatilidad    0.193540
SP.POP.GROW_volatilidad          0.189433
Name: SOCIODEMOGRAFICA_volatilidad_PC2, dtype: float64

============================================================

In [22]:
for dim in ["INSTITUCIONAL", "ESTRUCTURAL", "SOCIODEMOGRAFICA"]:
    nombre_bloque = f"{dim}_media"
    scores, cargas, var_exp, kmo, p = resultados_pca[nombre_bloque]
    print(f"=== {nombre_bloque} — PC1, mayor carga POSITIVA ===")
    print(cargas.iloc[:, 0].sort_values(ascending=False).head(5))
    print(f"\n=== {nombre_bloque} — PC1, mayor carga NEGATIVA ===")
    print(cargas.iloc[:, 0].sort_values(ascending=True).head(5))
    print("\n" + "="*60 + "\n")

=== INSTITUCIONAL_media — PC1, mayor carga POSITIVA ===
GOV_WGI_VA_SC_media     0.157129
GOV_WGI_VA_EST_media    0.157129
v2x_regime_amb_media    0.145854
GOV_WGI_RL_SC_media     0.142822
GOV_WGI_RL_EST_media    0.142822
Name: INSTITUCIONAL_media_PC1, dtype: float64

=== INSTITUCIONAL_media — PC1, mayor carga NEGATIVA ===
v2xnp_pres_media       -0.143512
v2x_pubcorr_media      -0.134935
v2xpe_exlsocgr_media   -0.134480
v2xpe_exlpol_media     -0.133924
v2x_execorr_media      -0.133531
Name: INSTITUCIONAL_media_PC1, dtype: float64

============================================================

=== ESTRUCTURAL_media — PC1, mayor carga POSITIVA ===
SL.EMP.WORK.ZS_media       0.178416
FB.ATM.TOTL.P5_media       0.168465
SL.GDP.PCAP.EM.KD_media    0.168107
NV.SRV.EMPL.KD_media       0.162885
SL.IND.EMPL.MA.ZS_media    0.162267
Name: ESTRUCTURAL_media_PC1, dtype: float64

=== ESTRUCTURAL_media — PC1, mayor carga NEGATIVA ===
SL.AGR.EMPL.ZS_media         -0.173935
NV.AGR.TOTL.ZS_media         -0.167967
SH.XPD.EHEX.CH.ZS_media      -0.139595
TM.TAX.MRCH.SM.AR.ZS_media   -0.137297
TM.VAL.TRAN.ZS.WT_media      -0.132591
Name: ESTRUCTURAL_media_PC1, dtype: float64

============================================================

=== SOCIODEMOGRAFICA_media — PC1, mayor carga POSITIVA ===
SP.POP.DPND.YG_media       0.157009
SH.STA.STNT.ME.ZS_media    0.147727
SE.PRM.ENRL.TC.ZS_media    0.142919
SP.ADO.TFRT_media          0.142840
SP.POP.1519.MA.5Y_media    0.140281
Name: SOCIODEMOGRAFICA_media_PC1, dtype: float64

=== SOCIODEMOGRAFICA_media — PC1, mayor carga NEGATIVA ===
SP.DYN.LE00.IN_media      -0.153914
SE.SEC.ENRR.MA_media      -0.152927
SH.STA.BASS.ZS_media      -0.152505
SP.DYN.TO65.FE.ZS_media   -0.149103
SH.H2O.BASW.ZS_media      -0.148179
Name: SOCIODEMOGRAFICA_media_PC1, dtype: float64

============================================================

## Exportamos

In [23]:
OUT_DIR = Path("data/processed")
OUT_DIR.mkdir(parents=True, exist_ok=True)

out_path = OUT_DIR / "15_pca_scores.xlsx"
df_pca_scores.to_excel(out_path, sheet_name="pca_scores")
print(f"Exportado: {out_path}")

Exportado: data\processed\15_pca_scores.xlsx

In [24]:
import pandas as pd
import numpy as np
from pathlib import Path

filas = []
for nombre_bloque, (scores, cargas, var_exp, kmo, p_valor) in resultados_pca.items():
    var_acum = np.cumsum(var_exp)
    n_retenidos = scores.shape[1]
    for i, (ve, va) in enumerate(zip(var_exp, var_acum), start=1):
        filas.append({
            "bloque": nombre_bloque,
            "componente": i,
            "var_explicada": ve,
            "var_acumulada": va,
            "retenido_original_70pct": i <= n_retenidos,
        })

df_varianza_pca = pd.DataFrame(filas)

OUT_PATH_VARIANZA = Path("data/processed/15_varianza_explicada_por_bloque.xlsx")
df_varianza_pca.to_excel(OUT_PATH_VARIANZA, index=False)
print(f"Exportado: {OUT_PATH_VARIANZA}")
print(f"Bloques: {df_varianza_pca['bloque'].nunique()} | Filas totales: {len(df_varianza_pca)}")

Exportado: data\processed\15_varianza_explicada_por_bloque.xlsx
Bloques: 12 | Filas totales: 1225

In [26]:
filas_completas = []
for nombre_bloque, (scores, cargas, var_exp, kmo, p_valor) in resultados_pca.items():
    n_comp = scores.shape[1]
    var_acum_pct = np.cumsum(var_exp)[n_comp - 1] * 100
    filas_completas.append({
        "bloque": nombre_bloque,
        "componentes": n_comp,
        "var_acum_pct": round(var_acum_pct, 1),
    })

df_componentes = pd.DataFrame(filas_completas)

df_resumen_pca_completo = pd.DataFrame(resumen_poda).merge(df_componentes, on="bloque")
df_resumen_pca_completo

,bloque,n_original,n_final,kmo_final,componentes,var_acum_pct
0,MONETARIA_media,140,63,0.701,11,71.7
1,MONETARIA_tendencia,140,60,0.601,13,71.4
2,MONETARIA_volatilidad,140,63,0.719,12,70.8
3,INSTITUCIONAL_media,80,80,0.915,5,70.3
4,INSTITUCIONAL_tendencia,80,80,0.805,13,71.2
5,INSTITUCIONAL_volatilidad,80,80,0.847,14,71.5
6,ESTRUCTURAL_media,207,120,0.614,16,70.8
7,ESTRUCTURAL_tendencia,207,118,0.603,19,70.2
8,ESTRUCTURAL_volatilidad,207,156,0.611,19,70.4
9,SOCIODEMOGRAFICA_media,258,124,0.796,10,71.0
10,SOCIODEMOGRAFICA_tendencia,258,139,0.605,21,70.2
11,SOCIODEMOGRAFICA_volatilidad,258,142,0.604,20,70.7